Repository facebookresearch/ParlAI, pull requests merged in 2018-08, with the labels that each got.

#1035 a few small fixes
  parlai/agents/seq2seq/seq2seq.py
  parlai/core/dict.py
  parlai/scripts/train_model.py
Labels: CLA Signed

#1037 Convai2 task fix
  parlai/mturk/tasks/convai2_model_eval/run.py
  parlai/mturk/tasks/convai2_model_eval/worlds.py
Labels: CLA Signed

#1038 fix reply by adding __start__ token when use persons_token True
  parlai/core/utils.py
Labels: CLA Signed

#1039 Update Flickr30k to include val/test split
  parlai/tasks/flickr30k/agents.py
  parlai/tasks/flickr30k/build.py
Labels: CLA Signed

#1040 Padding utils fix
  parlai/core/utils.py
Labels: CLA Signed

#1041 add images to torch agent batchify
  parlai/core/torch_agent.py
  parlai/tasks/coco_caption/agents.py
Labels: CLA Signed, enhancement, torchagent

#1042 Slight improvements to IR baseline
  parlai/agents/ir_baseline/ir_baseline.py
  parlai/tasks/squad/agents.py
Labels: CLA Signed

#966 Add Caption Retrieval Model
  parlai/agents/vsepp_caption/__init__.py
  parlai/agents/vsepp_caption/modules.py
  parlai/agents/vsepp_caption/vsepp_caption.py
  parlai/core/torch_agent.py
  parlai/tasks/coco_caption/agents.py
Labels: CLA Signed

#1044 CHNG: in convai2 we have changed a bit the URL format
  projects/convai/convai_world.py
Labels: CLA Signed

#1047 Update Coco Caption 2014 Splits
  parlai/tasks/coco_caption/agents.py
  parlai/tasks/coco_caption/build_2014.py
Labels: CLA Signed

#1050 Persona seq2seq fix
  projects/personachat/persona_seq2seq.py
Labels: CLA Signed

#1053 Sort opts when printing.
  parlai/core/params.py
Labels: CLA Signed

#1049 update torch agent with dialog history
  parlai/agents/example_seq2seq/example_seq2seq.py
  parlai/core/torch_agent.py
  tests/test_torch_agent.py
Labels: CLA Signed, enhancement, torchagent

#1051 Minor coco_caption fix
  parlai/tasks/coco_caption/agents.py
  parlai/tasks/flickr30k/agents.py
Labels: CLA Signed

#1055 Slightly better display_model output.
  parlai/core/utils.py
Labels: CLA Signed

#1029 PytorchDataTeacher Multitask Functionality
  docs/source/tutorial_worlds.rst
  parlai/core/params.py
  parlai/core/pytorch_data_teacher.py
  parlai/scripts/build_pytorch_data.py
  parlai/tasks/coco_caption/agents.py
  parlai/tasks/flickr30k/agents.py
Labels: CLA Signed

#1057 Allow force shuffle for pytorch data teacher
  parlai/core/params.py
  parlai/core/pytorch_data_teacher.py
Labels: CLA Signed

#1058 mturk arg for max hits per worker restriction and corresponding counter
  parlai/core/params.py
  parlai/mturk/core/mturk_manager.py
Labels: CLA Signed

#1059 Convai2 engagingness test fixes
  parlai/mturk/tasks/convai2_model_eval/run.py
  parlai/mturk/tasks/convai2_model_eval/worlds.py
Labels: CLA Signed

#1063 Fix a bug when using model replies and ending episodes.
  parlai/core/torch_agent.py
  tests/test_torch_agent.py
Labels: CLA Signed

#1065 Revert "Cache txt2vec items."
  parlai/core/dict.py
Labels: CLA Signed

#1072 Clean up some of the lowercase stuff
  parlai/core/dict.py
  projects/personachat/persona_seq2seq.py
Labels: CLA Signed

#1074 Throw away empty vector items from the batch.
  parlai/agents/fairseq/fairseq.py
Labels: CLA Signed, bug, torchagent

#1075 Small fix convai2 model eval
  parlai/mturk/tasks/convai2_model_eval/run.py
Labels: CLA Signed

#1073 Get rid of persona_seq2seq Convai2 baseline code
  projects/convai2/baselines/profilememory/eval_f1.py
  projects/convai2/baselines/profilememory/eval_hits.py
  projects/convai2/baselines/profilememory/eval_ppl.py
  projects/convai2/baselines/profilememory/interactive.py
  projects/convai2/baselines/profilememory/train.py
Labels: CLA Signed

#1079 DRY out Squad a bit.
  parlai/tasks/squad/agents.py
Labels: CLA Signed

#1084 poppin' pop bug
  parlai/core/teachers.py
Labels: CLA Signed

#1086 Persona seq2seq remove unnecessary lines
  projects/personachat/persona_seq2seq.py
Labels: CLA Signed

#1076 Delete old submodules file.
  .gitmodules
Labels: CLA Signed

#1077 Setting namedtuple defaults utility.
  parlai/core/torch_agent.py
  parlai/core/utils.py
  tests/test_utils.py
Labels: CLA Signed

#1088 Add ability to specify number of cands in Flickr30k
  parlai/tasks/coco_caption/agents.py
  parlai/tasks/flickr30k/agents.py
Labels: CLA Signed

#1090 Separate out some logic from f1 score for reuse elsewhere.
  parlai/core/metrics.py
Labels: CLA Signed

#1091 Don't save a TorchAgent model on shutdown.
  parlai/core/torch_agent.py
Labels: CLA Signed

#1078 Adjust some TorchAgent/Fairseq API for easier extension.
  parlai/agents/fairseq/fairseq.py
  parlai/core/torch_agent.py
  tests/test_torch_agent.py
Labels: CLA Signed

#1052 Implement fairseq candidate ranking using generator.
  parlai/agents/fairseq/fairseq.py
  parlai/core/torch_agent.py
  parlai/core/utils.py
  tests/run_tests_short.sh
  tests/test_torch_agent.py
  tests/test_utils.py
Labels: CLA Signed

#1096 Add flag for multiple GPUs. User must manually support this.
  parlai/core/torch_agent.py
Labels: CLA Signed

#1095 Clean up squad sentence teachers
  parlai/tasks/squad/agents.py
Labels: CLA Signed

#1098 Add TorchAgent to Sphinx docs.
  docs/source/index.rst
  docs/source/torch_agent.rst
Labels: CLA Signed

#1036 ParlAI-Mturk Refactor with new testing
  .travis.yml
  parlai/mturk/core/agents.py
  parlai/mturk/core/mturk_manager.py
  parlai/mturk/core/server/html/core.html
  parlai/mturk/core/server/server.js
  parlai/mturk/core/socket_manager.py
  parlai/mturk/core/test/integration_test/__init__.py
  parlai/mturk/core/test/integration_test/integration_test.py
  parlai/mturk/core/test/integration_test/worlds.py
  parlai/mturk/core/test/test_full_system.py
  parlai/mturk/core/test/test_mturk_agent.py
  parlai/mturk/core/test/test_mturk_manager.py
  parlai/mturk/core/test/test_socket_manager.py
  parlai/mturk/core/test/test_worker_manager.py
  parlai/mturk/core/worker_manager.py
  parlai/mturk/core/worker_state.py
  tests/run_mturk_tests_if_needed.sh
Labels: CLA Signed

#1101 Squad full doc sentence teacher bug fix
  parlai/tasks/squad/agents.py
Labels: CLA Signed

#1100 Fixes small bug in acting after a disconnect (disconnect comes first)
  parlai/mturk/core/agents.py
  parlai/mturk/core/test/test_socket_manager.py
Labels: CLA Signed

#1099 create legacy_agents folder and copy seq2seq to it
  parlai/legacy_agents/__init__.py
  parlai/legacy_agents/seq2seq/__init__.py
  parlai/legacy_agents/seq2seq/modules_v0.py
  parlai/legacy_agents/seq2seq/seq2seq_v0.py
Labels: CLA Signed

#1021 print total time for build_dict, update dictionary docstrings
  parlai/core/dict.py
  parlai/scripts/build_dict.py
Labels: CLA Signed

#1105 update model_zoo paths in more places
  parlai/core/dict.py
  parlai/core/params.py
Labels: CLA Signed

#1106 add functionality for tensors to utils.padded_tensor
  parlai/core/utils.py
Labels: CLA Signed

#1108 fix attnmask in s2s decoding w.o attn
  parlai/agents/seq2seq/modules.py
Labels: CLA Signed

#1104 add check for model version when loading opt
  parlai/core/agents.py
Labels: CLA Signed

#1109 upgrade torch agent with s2s features
  parlai/core/torch_agent.py
Labels: CLA Signed

#1113 TorchAgent and Fairseq fixes/enhancements
  parlai/agents/fairseq/fairseq.py
  parlai/core/torch_agent.py
  tests/test_torch_agent.py
Labels: CLA Signed

#1116 support cmd line args for pytorch datasets
  parlai/core/params.py
  parlai/scripts/build_pytorch_data.py
  parlai/tasks/coco_caption/agents.py
  parlai/tasks/flickr30k/agents.py
Labels: CLA Signed

#1102 Add checks for copyright messages in travis.
  .travis.yml
  docs/source/coopgame_agent.rst
  examples/display_model.py
  examples/extract_image_feature.py
  examples/remote.py
  parlai/agents/coopgame_agent/coopgame_agent.py
  parlai/agents/mlb_vqa/mlb_vqa.py
  parlai/agents/tfidf_retriever/tokenizers/__init__.py
  parlai/agents/tfidf_retriever/tokenizers/corenlp_tokenizer.py
  parlai/agents/tfidf_retriever/tokenizers/regexp_tokenizer.py
  parlai/agents/tfidf_retriever/tokenizers/simple_tokenizer.py
  parlai/agents/tfidf_retriever/tokenizers/spacy_tokenizer.py
  parlai/agents/tfidf_retriever/tokenizers/tokenizer.py
  parlai/agents/tfidf_retriever/utils.py
  parlai/core/image_featurizers.py
  parlai/mturk/core/test/test_full_system.py
  parlai/mturk/core/test/test_mturk_agent.py
  parlai/mturk/core/test/test_mturk_manager.py
  parlai/mturk/core/test/test_socket_manager.py
  parlai/mturk/core/test/test_worker_manager.py
  parlai/scripts/extract_image_feature.py
  parlai/tasks/dialog_babi_plus/__init__.py
  parlai/tasks/dialog_babi_plus/agents.py
  parlai/tasks/dialog_babi_plus/build.py
  parlai/tasks/fvqa/__init__.py
  parlai/tasks/fvqa/agents.py
  parlai/tasks/fvqa/build.py
  parlai/tasks/taskntalk/__init__.py
  parlai/tasks/taskntalk/agents.py
  parlai/tasks/taskntalk/build.py
  projects/babi/memnn/memnn_bAbI_10k_task_parameter_sweep.sh
  projects/babi/memnn/memnn_bAbI_1k_task_parameter_sweep.sh
  projects/drqa/eval_full.sh
  projects/personachat/scripts/kvmemnn_train.sh
  projects/personachat/scripts/profilememory_train.sh
  tests/check_copyright.sh
  tests/tasks/convai_chitchat/TeacherTest.py
  tests/test_tfidf_retriever.py
Labels: CLA Signed

#1092 Touch it, fix it. Add strict linting to changed files.
  .flake8
  .travis.yml
  tests/lint_changed.sh
Labels: CLA Signed

#1117 Lint everything Jaseweston has touched in the past two months
  parlai/agents/ir_baseline/ir_baseline.py
  parlai/agents/repeat_label/repeat_label.py
  parlai/scripts/eval_wordstat.py
  parlai/tasks/squad/agents.py
  parlai/tasks/twitter/build.py
  parlai/zoo/model_list.py
Labels: CLA Signed

#1124 Remove linting of full codebase from travis.
  .travis.yml
Labels: CLA Signed

#1121 fix the predict function of s2s model
  parlai/agents/seq2seq/seq2seq.py
Labels: CLA Signed

#1054 Fixes to FP16 with fairseq master.
  parlai/agents/fairseq/fairseq.py
Labels: CLA Signed, fairseq

#1119 new version of seq2seq
  parlai/agents/seq2seq/modules.py
  parlai/agents/seq2seq/seq2seq.py
  parlai/core/torch_agent.py
Labels: CLA Signed

#1125 move convai2 model to legacy seq2seq
  projects/convai2/baselines/seq2seq/eval_f1.py
  projects/convai2/baselines/seq2seq/eval_hits.py
  projects/convai2/baselines/seq2seq/eval_ppl.py
  projects/convai2/baselines/seq2seq/eval_wordstat.py
  projects/convai2/baselines/seq2seq/interactive.py
  projects/convai2/baselines/seq2seq/train.py
Labels: CLA Signed, convai2, torchagent

#1110 switch seq2seq parent class to TorchAgent
  parlai/agents/seq2seq/modules.py
  parlai/agents/seq2seq/seq2seq.py
  parlai/core/torch_agent.py
  tests/test_torch_agent.py
Labels: CLA Signed, torchagent

#1127 Enc out expand fix
  parlai/agents/seq2seq/modules.py
Labels: CLA Signed

#1126 fully isolate seq2seq legacy code from rest of parlai
  parlai/legacy_agents/seq2seq/dict_v0.py
  parlai/legacy_agents/seq2seq/modules_v0.py
  parlai/legacy_agents/seq2seq/seq2seq_v0.py
  parlai/legacy_agents/seq2seq/utils_v0.py
Labels: CLA Signed, torchagent

#1118 Database State for ParlAI-MTurk
  parlai/mturk/core/mturk_data_handler.py
  parlai/mturk/core/mturk_manager.py
  parlai/mturk/core/mturk_utils.py
  parlai/mturk/core/socket_manager.py
  parlai/mturk/core/test/test_db_interactions.py
  parlai/mturk/core/test/test_full_system.py
  parlai/mturk/core/test/test_mturk_manager.py
  parlai/mturk/core/test/test_socket_manager.py
  tests/run_mturk_tests_if_needed.sh
Labels: CLA Signed
