Repository facebookresearch/ParlAI, pull requests merged in 2018-12, with the labels that each got.

#1301 look for local dict file, this was set wrong
  parlai/agents/starspace/starspace.py
Labels: CLA Signed

#1284 remove lua torch from readme paragraph
  README.md
Labels: CLA Signed

#1306 Add personas feature to ParlAI Messenger
  parlai/messenger/core/message_sender.py
Labels: CLA Signed

#1280 update ranking error message
  parlai/core/torch_agent.py
  parlai/core/torch_ranker_agent.py
Labels: CLA Signed

#1307 fix for batched executable worlds
  parlai/core/worlds.py
Labels: CLA Signed

#1308 [MTurk] Demo react tasks in webapp frontend
  parlai/mturk/core/agents.py
  parlai/mturk/core/react_server/dev/app.jsx
  parlai/mturk/core/react_server/dev/components/core_components.jsx
  parlai/mturk/core/react_server/dev/components/mturk_submit_form.jsx
  parlai/mturk/core/react_server/server/static/index.html
  parlai/mturk/tasks/react_task_demo/react_custom_no_extra_deps/frontend/components/custom.jsx
  parlai/mturk/tasks/react_task_demo/react_custom_no_extra_deps/run.py
  parlai/mturk/tasks/react_task_demo/react_custom_with_deps/frontend/components/custom.jsx
  parlai/mturk/tasks/react_task_demo/react_custom_with_deps/run.py
  parlai/mturk/webapp/dev/app.jsx
  parlai/mturk/webapp/run_mocks/mock_turk_agent.py
  parlai/mturk/webapp/run_mocks/mock_turk_manager.py
  parlai/mturk/webapp/server.py
Labels: CLA Signed, MTurk, enhancement

#1314 [MTurk] Forcing dummy custom dist to be included
  parlai/mturk/core/react_server/dev/components/built_custom_components/dist/custom.jsx
Labels: CLA Signed, MTurk, bug

#1312 Add Daily Dialog task.
  parlai/tasks/dailydialog/__init__.py
  parlai/tasks/dailydialog/agents.py
  parlai/tasks/dailydialog/build.py
  parlai/tasks/dailydialog/parse.py
  parlai/tasks/task_list.py
  tests/test_new_tasks.py
Labels: CLA Signed

#1315 [MTurk] Making mturk socket tests skip on travis
  parlai/mturk/core/test/test_full_system.py
  parlai/mturk/core/test/test_mturk_manager.py
  parlai/mturk/core/test/test_socket_manager.py
Labels: CLA Signed, MTurk

#1321 [MTurk] Fixing dual mturk world init problem.
  parlai/mturk/core/mturk_manager.py
Labels: CLA Signed

#1322 Additionally pass the observations to Batch objects.
  parlai/core/torch_agent.py
Labels: CLA Signed

#1325 [Messenger] observing personas
  parlai/messenger/core/agents.py
  parlai/messenger/core/messenger_manager.py
Labels: CLA Signed

#1323 [MTurk] Evaluate chat partner on 2 person tasks
  parlai/mturk/core/agents.py
  parlai/mturk/core/mturk_data_handler.py
  parlai/mturk/core/mturk_manager.py
  parlai/mturk/core/mturk_utils.py
  parlai/mturk/core/react_server/dev/app.jsx
  parlai/mturk/core/react_server/dev/components/core_components.jsx
  parlai/mturk/core/react_server/dev/components/socket_handler.jsx
  parlai/mturk/core/react_server/server/server.js
  parlai/mturk/core/react_server/server/static/index.html
  parlai/mturk/core/socket_manager.py
  parlai/mturk/core/test/test_mturk_manager.py
  parlai/mturk/core/worlds.py
  parlai/mturk/tasks/multi_agent_dialog/run.py
  parlai/mturk/tasks/qa_data_collection/task_config.py
  parlai/mturk/webapp/dev/app.jsx
  parlai/mturk/webapp/static/index.html
Labels: CLA Signed
