Repository facebookresearch/ParlAI, pull requests merged in 2018-10, with the labels that each got.

#1188 Ngram block for beam search, blocks all repeating ngrams up to n
  parlai/agents/seq2seq/seq2seq.py
  parlai/core/torch_agent.py
Labels: CLA Signed

#1189 [ParlAI Messenger] fix for image sending
  parlai/messenger/core/agents.py
  parlai/messenger/core/messenger_manager.py
Labels: CLA Signed

#1187 Lint docs and examples
  docs/source/conf.py
  docs/source/generate_task_list.py
  examples/display_model.py
  examples/memnn_luatorch_cpu/full_task_train.py
  examples/train_model.py
Labels: CLA Signed

#1191 Async is a reserved word in Python 3.7.
  parlai/agents/drqa/model.py
  parlai/agents/vsepp_caption/vsepp_caption.py
  projects/personachat/persona_seq2seq.py
Labels: CLA Signed

#1186 Lint all of parlai
  .flake8
  parlai/agents/coopgame_agent/coopgame_agent.py
  parlai/agents/drqa/drqa.py
  parlai/agents/ibm_seq2seq/ibm_seq2seq.py
  parlai/agents/language_model/modules.py
  parlai/agents/mlb_vqa/mlb_modules.py
  parlai/agents/mlb_vqa/mlb_vqa.py
  parlai/agents/starspace/starspace.py
  parlai/agents/vsepp_caption/vsepp_caption.py
  parlai/core/metrics.py
  parlai/messenger/core/__init__.py
  parlai/mturk/core/__init__.py
  parlai/mturk/tasks/convai2_model_eval/run.py
  parlai/mturk/tasks/convai2_model_eval/worlds.py
  parlai/mturk/tasks/dealnodeal/worlds.py
  parlai/mturk/tasks/multi_agent_dialog/run.py
  parlai/mturk/tasks/personachat/personachat_chat/run.py
  parlai/mturk/tasks/personachat/personachat_collect_personas/run.py
  parlai/mturk/tasks/talkthewalk/download.py
  parlai/mturk/tasks/talkthewalk/worlds.py
  parlai/scripts/build_dict.py
  parlai/scripts/build_pytorch_data.py
  parlai/scripts/display_data.py
  parlai/scripts/eval_model.py
  parlai/scripts/eval_ppl.py
  parlai/scripts/profile_train.py
  parlai/tasks/booktest/agents.py
  parlai/tasks/clevr/agents.py
  parlai/tasks/coco_caption/agents.py
  parlai/tasks/convai2/agents.py
  parlai/tasks/convai_chitchat/agents.py
  parlai/tasks/convai_chitchat/build.py
  parlai/tasks/dealnodeal/agents.py
  parlai/tasks/dialog_babi/agents.py
  parlai/tasks/dialog_babi_plus/agents.py
  parlai/tasks/dialog_babi_plus/build.py
  parlai/tasks/dialogue_qe/agents.py
  parlai/tasks/dialogue_qe/build.py
  parlai/tasks/flickr30k/agents.py
  parlai/tasks/fvqa/agents.py
  parlai/tasks/fvqa/build.py
  parlai/tasks/insuranceqa/build.py
  parlai/tasks/integration_tests/agents.py
  parlai/tasks/ms_marco/build.py
  parlai/tasks/mturkwikimovies/build.py
  parlai/tasks/mutualfriends/agents.py
  parlai/tasks/mutualfriends/build.py
  parlai/tasks/nlvr/agents.py
  parlai/tasks/opensubtitles/agents.py
  parlai/tasks/opensubtitles/build_2018.py
  parlai/tasks/personalized_dialog/agents.py
  parlai/tasks/taskntalk/build.py
  parlai/tasks/tasks.py
  parlai/tasks/triviaqa/agents.py
  parlai/tasks/visdial/agents.py
  parlai/tasks/vqa_v1/agents.py
  parlai/tasks/vqa_v2/agents.py
  parlai/tasks/wikipedia/agents.py
Labels: CLA Signed

#1185 Don't use a fixed CLI description.
  examples/display_model.py
  parlai/core/params.py
  parlai/scripts/build_dict.py
  parlai/scripts/build_pytorch_data.py
  parlai/scripts/detect_offensive_language.py
  parlai/scripts/display_data.py
  parlai/scripts/eval_model.py
  parlai/scripts/eval_ppl.py
  parlai/scripts/eval_wordstat.py
  parlai/scripts/extract_image_feature.py
  parlai/scripts/interactive.py
  parlai/scripts/profile_train.py
  parlai/scripts/train_model.py
  parlai/scripts/verify_data.py
Labels: CLA Signed, docs

#1181 Fairseq 0.6
  parlai/agents/fairseq/fairseq.py
Labels: CLA Signed

#1190 Autogenerated docs for model zoo (incomplete)
  .gitignore
  docs/Makefile
  docs/source/generate_zoo_list.py
  docs/source/index.rst
  docs/source/zoo.rst
Labels: CLA Signed, docs

#1183 Autogenerate docs for each of the CLI scripts we distribute.
  .gitignore
  docs/Makefile
  docs/source/cli_usage.rst
  docs/source/generate_cli.py
  docs/source/index.rst
  parlai/scripts/eval_wordstat.py
Labels: CLA Signed, docs

#1182 Organize tests
  .travis.yml
  CONTRIBUTING.md
  setup.py
  tests/__init__.py
  tests/check_copyright.sh
  tests/integration/test_downloads.py
  tests/integration/test_fairseq.py
  tests/integration/test_mlb_vqa.py
  tests/run_mturk_tests_if_needed.sh
  tests/run_tests_long.sh
  tests/run_tests_short.sh
  tests/suites.py
  tests/tasks/convai_chitchat/TeacherTest.py
  tests/test_code.py
  tests/test_init.py
  tests/test_tfidf_retriever.py
  tests/test_threadutils.py
  tests/utils.py
Labels: CLA Signed

#1194 Slightly change how display_messages looks.
  parlai/core/utils.py
Labels: CLA Signed

#1157 --display-ignore-fields in display_model.
  examples/display_model.py
Labels: CLA Signed

#1198 remove debug code from MemnnAgent
  parlai/agents/memnn/memnn.py
Labels: bug

#1202 Adds documentation for the qa_data_collection world
  parlai/mturk/core/worlds.py
  parlai/mturk/tasks/qa_data_collection/run.py
  parlai/mturk/tasks/qa_data_collection/worlds.py
Labels: CLA Signed

#1204 Force string display messages
  parlai/core/utils.py
Labels: CLA Signed

#1203 README for tfidf_retriever
  parlai/agents/tfidf_retriever/README.md
Labels: CLA Signed

#1206 CLI arg doc changes
  docs/source/generate_cli.py
  docs/source/index.rst
  docs/source/utils.rst
  examples/build_dict.py
  examples/build_pytorch_data.py
  examples/display_data.py
  examples/display_model.py
  examples/eval_model.py
  examples/extract_image_feature.py
  examples/interactive.py
  examples/profile_train.py
  examples/train_model.py
  parlai/agents/fairseq/fairseq.py
  parlai/core/agents.py
  parlai/core/dict.py
  parlai/core/torch_agent.py
  parlai/scripts/build_dict.py
  parlai/scripts/build_pytorch_data.py
  parlai/scripts/convert_data_to_parlai_format.py
  parlai/scripts/detect_offensive_language.py
  parlai/scripts/display_data.py
  parlai/scripts/display_model.py
  parlai/scripts/eval_model.py
  parlai/scripts/eval_wordstat.py
  parlai/scripts/extract_image_feature.py
  parlai/scripts/interactive.py
  parlai/scripts/profile_train.py
  parlai/scripts/train_model.py
  parlai/scripts/verify_data.py
Labels: CLA Signed

#1207 Unigram Agent
  docs/source/index.rst
  docs/source/unigram_agent.rst
  parlai/agents/unigram/README.md
  parlai/agents/unigram/__init__.py
  parlai/agents/unigram/unigram.py
Labels: CLA Signed

#1208 Standardize readme format
  parlai/agents/unigram/README.md
Labels: CLA Signed

#1209 READMEs for mlb_vqa and vsepp_caption
  parlai/agents/mlb_vqa/README.md
  parlai/agents/vsepp_caption/README.md
  parlai/agents/vsepp_caption/modules.py
  parlai/agents/vsepp_caption/vsepp_caption.py
Labels: CLA Signed

#1212 tqdm progress bar, smart num examples, random tmp files for output
  parlai/scripts/convert_data_to_parlai_format.py
Labels: CLA Signed

#1211 Deprecate memnn_luatorch_cpu
  README.md
  examples/README.md
  parlai/agents/legacy_agents/memnn_luatorch_cpu/__init__.py
  parlai/agents/legacy_agents/memnn_luatorch_cpu/examples/__init__.py
  parlai/agents/legacy_agents/memnn_luatorch_cpu/examples/full_task_train.py
  parlai/agents/legacy_agents/memnn_luatorch_cpu/examples/params_default.lua
  parlai/agents/legacy_agents/memnn_luatorch_cpu/memnn_agent.lua
  parlai/agents/legacy_agents/memnn_luatorch_cpu/memnn_agent_parsed.lua
  parlai/agents/legacy_agents/memnn_luatorch_cpu/memnn_zmq.lua
  parlai/agents/legacy_agents/memnn_luatorch_cpu/memnn_zmq_parsed.lua
  tests/check_examples.sh
Labels: CLA Signed

#1214 ConvAI: replacing '/start' with 'Your persona:'
  projects/convai/convai_world.py
Labels: CLA Signed

#1216 Use valid_world's batchsize in run_eval()
  parlai/scripts/train_model.py
Labels: CLA Signed

#1205 command to print unit test coverage
  requirements.txt
  tests/coverage.sh
Labels: CLA Signed

#1071 Convai wild evaluation dataset task
  parlai/tasks/convai2_wild_evaluation/__init__.py
  parlai/tasks/convai2_wild_evaluation/agents.py
  parlai/tasks/convai2_wild_evaluation/build.py
  parlai/tasks/task_list.py
Labels: CLA Signed

#1218 ConvAI: fixes by bug report
  projects/convai/convai_bot.py
  projects/convai/convai_world.py
Labels: CLA Signed

#1220 ConvAI: correct ending check
  projects/convai/convai_world.py
Labels: CLA Signed

#1200 Missing fairseq option.
  parlai/agents/fairseq/fairseq.py
Labels: CLA Signed

#1199 Reorganize how TorchAgent does vectorize/batchify.
  parlai/core/torch_agent.py
Labels: CLA Signed

#1213 Making socket manager dual-threaded rather than multi
  parlai/mturk/core/socket_manager.py
  parlai/mturk/core/test/test_socket_manager.py
Labels: CLA Signed

#1219 ParlaiDialogTeacher: save last episode and make parsing friendlier
  docs/source/tutorial_task.rst
  parlai/core/teachers.py
Labels: CLA Signed

#1225 Make sure RepeatTeacher doesn't leak files.
  tests/tasks/repeat.py
Labels: CLA Signed

#1227 add memnn integration and multiturn integration test
  parlai/agents/memnn/memnn.py
  parlai/tasks/integration_tests/agents.py
  tests/integration/test_memnn.py
  tests/integration/test_seq2seq.py
  tests/test_train_model.py
Labels: CLA Signed

#1230 Add code of conduct.
  CODE_OF_CONDUCT.md
Labels: CLA Signed

#1229 seq2seq multiturn test, move memnn & seq2seq out of integration
  parlai/tasks/integration_tests/agents.py
  tests/test_memnn.py
  tests/test_seq2seq.py
Labels: CLA Signed

#1236 Copyright on an additional file.
  docs/source/_static/css/parlai_theme.css
  tests/test_code.py
Labels: CLA Signed

#1241 starspace: input feature dropout
  parlai/agents/starspace/starspace.py
Labels: CLA Signed

#1221 [wip] TorchRankerAgent abstract class
  .travis.yml
  parlai/agents/memnn/memnn.py
  parlai/agents/seq2seq/seq2seq.py
  parlai/core/torch_agent.py
  parlai/core/torch_ranker_agent.py
  parlai/tasks/task_list.py
  tests/test_torch_agent.py
Labels: CLA Signed

#1242 Hide advanced option unless asked by the user.
  parlai/core/dict.py
  parlai/core/logs.py
  parlai/core/params.py
  parlai/scripts/train_model.py
Labels: CLA Signed

#1240 switch pickle to json for opt files
  parlai/agents/drqa/drqa.py
  parlai/agents/fairseq/fairseq.py
  parlai/agents/language_model/language_model.py
  parlai/agents/seq2seq/seq2seq.py
  parlai/agents/starspace/starspace.py
  parlai/agents/tfidf_retriever/tfidf_retriever.py
  parlai/agents/unigram/unigram.py
  parlai/core/agents.py
  parlai/core/dict.py
  parlai/core/params.py
  parlai/core/torch_agent.py
Labels: CLA Signed

#1248 Fix for `max_hits_per_worker`
  parlai/mturk/core/mturk_manager.py
Labels: CLA Signed

#1249 Personality Captions
  NEWS.md
  parlai/tasks/personality_captions/__init__.py
  parlai/tasks/personality_captions/agents.py
  parlai/tasks/personality_captions/build.py
  parlai/tasks/personality_captions/download_images.py
  parlai/tasks/task_list.py
Labels: CLA Signed

#1250 Fix for params.py
  parlai/core/params.py
Labels: CLA Signed

#1251 [MTurk] Allowed conversations should not be greater than max workers
  parlai/mturk/core/mturk_manager.py
Labels: CLA Signed

#1252 PMT Frontend webapp
  parlai/mturk/core/mturk_data_handler.py
  parlai/mturk/webapp/.babelrc
  parlai/mturk/webapp/.gitignore
  parlai/mturk/webapp/dev/app.jsx
  parlai/mturk/webapp/dev/css/style.css
  parlai/mturk/webapp/dev/main.js
  parlai/mturk/webapp/package.json
  parlai/mturk/webapp/server.py
  parlai/mturk/webapp/static/index.html
  parlai/mturk/webapp/webpack.config.js
Labels: CLA Signed

#1222 Multi GPU support for seq2seq
  parlai/agents/seq2seq/modules.py
  parlai/agents/seq2seq/seq2seq.py
  parlai/core/utils.py
Labels: CLA Signed

#1253 [MTurk] Universal task saving 'format'
  parlai/mturk/core/.gitignore
  parlai/mturk/core/agents.py
  parlai/mturk/core/mturk_data_handler.py
  parlai/mturk/core/mturk_manager.py
  parlai/mturk/core/worlds.py
  parlai/mturk/tasks/qa_data_collection/run.py
  parlai/mturk/tasks/qa_data_collection/worlds.py
Labels: CLA Signed

#1244 Model Zoo documentation improvements
  docs/source/generate_zoo_list.py
  parlai/agents/unigram/unigram.py
  parlai/zoo/model_list.py
Labels: CLA Signed

#1243 Don't track *.length files
  .gitignore
Labels: CLA Signed

#1256 verify_data script should stream
  parlai/scripts/verify_data.py
Labels: CLA Signed

#1259 fix wmt datatype checking
  parlai/tasks/wmt/agents.py
Labels: CLA Signed
