Repository facebookresearch/ParlAI, pull requests merged in 2018-06, with the labels that each got.

#802 Fix args injection inside add_extra_args
  parlai/core/params.py
Labels: CLA Signed

#800 DrQA training script
  parlai/agents/drqa/config.py
  parlai/agents/drqa/drqa.py
  parlai/core/build_data.py
  parlai/core/params.py
  parlai/core/utils.py
  parlai/scripts/eval_model.py
  parlai/zoo/glove_vectors/__init__.py
  parlai/zoo/glove_vectors/build.py
  projects/drqa/train.py
Labels: CLA Signed

#803 Tfidf retriever for Wikipedia in model zoo!
  parlai/zoo/wikipedia_full/__init__.py
  parlai/zoo/wikipedia_full/tfidf_retriever.py
Labels: CLA Signed

#801 internal shortcut
  parlai/core/agents.py
Labels: CLA Signed

#804 Validation metric as subtask metric
  parlai/scripts/train_model.py
Labels: CLA Signed

#807 f string syntax rollback to .format syntax
  parlai/core/build_data.py
Labels: CLA Signed

#812 Messenger fix for logging compatibility
  parlai/messenger/core/agents.py
Labels: CLA Signed

#810 Make persona_seq2seq scripts compatible with pytorch 0.4.0
  projects/personachat/persona_seq2seq.py
Labels: CLA Signed

#814 fix convai2 seq2seq baseline loading
  projects/convai2/baselines/seq2seq/eval_f1.py
  projects/convai2/baselines/seq2seq/eval_hits.py
  projects/convai2/baselines/seq2seq/eval_ppl.py
Labels: CLA Signed

#815 Push optimizer to gpu for persona_seq2seq
  projects/personachat/persona_seq2seq.py
Labels: CLA Signed

#798 Tensorboard log with tensorboardx package in train_model.py script
  docs/Makefile
  docs/source/index.rst
  docs/source/tutorial_tensorboard.rst
  docs/source/tutorial_worlds.rst
  parlai/core/logs.py
  parlai/core/params.py
  parlai/scripts/train_model.py
  parlai/tasks/twitter/build.py
Labels: CLA Signed

#786 fix starspace for new pytorch
  parlai/agents/starspace/modules.py
  parlai/agents/starspace/starspace.py
Labels: CLA Signed

#816 if logic for deque with truncation case
  parlai/core/utils.py
Labels: CLA Signed

#818 update to work with drqa wiki dump
  parlai/agents/tfidf_retriever/tfidf_doc_ranker.py
  parlai/agents/tfidf_retriever/tfidf_retriever.py
Labels: CLA Signed

#817 skip loading dict during training
  parlai/scripts/build_dict.py
  parlai/scripts/train_model.py
Labels: CLA Signed

#821 tfidf_retriever: fix missing arg
  parlai/agents/tfidf_retriever/tfidf_retriever.py
Labels: CLA Signed

#819 fix unit tests
  parlai/agents/tfidf_retriever/tfidf_retriever.py
  parlai/zoo/__init__.py
Labels: CLA Signed

#820 fix flake8 errors in various files
  parlai/agents/coopgame_agent/coopgame_agent.py
  parlai/agents/language_model/language_model.py
  parlai/agents/tfidf_retriever/doc_db.py
  parlai/scripts/profile_train.py
  parlai/tasks/wikiqa/build.py
  projects/convai2/baselines/profilememory/eval_hits.py
  projects/mastering_the_dungeon/agents/graph_world2/models.py
  projects/personachat/mturk/personachat_eval/extract_and_save_personas.py
  projects/personachat/mturk/personachat_eval/run.py
  projects/personachat/mturk/personachat_eval/worlds.py
Labels: CLA Signed

#824 Zoo model list + add classic drqa retriever to zoo
  parlai/zoo/model_list.py
  parlai/zoo/wikipedia_2016-12-21/__init__.py
  parlai/zoo/wikipedia_2016-12-21/tfidf_retriever.py
Labels: CLA Signed

#266 Add free automated flake8 testing on all pull requests
  .travis.yml
Labels: CLA Signed, enhancement

#825 Fix bug that loads only one example for first batch
  parlai/tasks/coco_caption/agents.py
  parlai/tasks/flickr30k/agents.py
  parlai/tasks/vqa_v1/agents.py
  parlai/tasks/vqa_v2/agents.py
Labels: CLA Signed

#827 slightly prettier display in interactive and beyond
  examples/interactive.py
  parlai/agents/local_human/local_human.py
  parlai/agents/starspace/starspace.py
  parlai/core/utils.py
  parlai/core/worlds.py
  parlai/scripts/interactive.py
Labels: CLA Signed

#829 Fix for when batch size becomes to 1 at test time.
  parlai/core/agents.py
Labels: CLA Signed

#833 train:evalmode, where labels are hidden
  parlai/core/params.py
  parlai/core/teachers.py
Labels: CLA Signed

#832 Make persona_seq2seq work without gpu
  projects/personachat/persona_seq2seq.py
Labels: CLA Signed

#841 Fix training script for persona_seq2seq model
  projects/convai2/baselines/profilememory/train.py
Labels: CLA Signed

#830 Update pytorch datateacher docs
  docs/source/tutorial_worlds.rst
Labels: CLA Signed

#842 remove cheat option on convai2 eval
  parlai/scripts/eval_ppl.py
Labels: CLA Signed

#837 Update TorchAgent with standard functions and fix small bug
  parlai/core/torch_agent.py
Labels: CLA Signed

#845 utility improvements to seq2seq
  parlai/agents/drqa/drqa.py
  parlai/agents/seq2seq/seq2seq.py
Labels: CLA Signed

#848 detect offensive language bug
  parlai/scripts/detect_offensive_language.py
Labels: CLA Signed

#850 Fix 'NoneType' object is not iterable
  projects/personachat/kvmemnn/kvmemnn.py
Labels: CLA Signed

#847 Enables setting Daily Work Time Limitation by workers
  docs/source/tutorial_mturk.rst
  parlai/core/params.py
  parlai/mturk/core/agents.py
  parlai/mturk/core/mturk_manager.py
Labels: CLA Signed

#851 small doc updates: messenger
  README.md
Labels: CLA Signed

#854 Some doc cleanup, including better looking task list
  docs/source/generate_task_list.py
  docs/source/index.rst
  docs/source/tasks.rst
  docs/source/tutorial_basic.rst
Labels: CLA Signed

#853 [MTurk] Fixing thread safety for time lock file
  parlai/mturk/core/mturk_manager.py
Labels: CLA Signed

#855 Updates to basic docs + data handling docs
  .gitignore
  docs/source/tutorial_basic.rst
  docs/source/tutorial_worlds.rst
Labels: CLA Signed

#852 Making it possible to determine the split location in long messages
  parlai/messenger/core/message_sender.py
Labels: CLA Signed

#857 fix kvmemnn bug
  projects/personachat/kvmemnn/kvmemnn.py
Labels: CLA Signed

#859 Messenger docs
  docs/source/_static/img/personachat_example.png
  docs/source/tutorial_messenger.rst
Labels: CLA Signed

#865 tb logger formating fixes, add text
  parlai/core/logs.py
Labels: CLA Signed

#864 eval_wordstat script
  parlai/scripts/eval_wordstat.py
Labels: CLA Signed

#861 [MTurk] Optionally banning mobile
  parlai/mturk/core/server/html/core.html
Labels: CLA Signed

#862 [MTurk] Tips and Tricks in docs
  docs/source/tutorial_mturk.rst
Labels: CLA Signed

#863 Subsample docs for full doc training in drqa
  parlai/agents/drqa/config.py
  parlai/agents/drqa/drqa.py
  parlai/agents/drqa/utils.py
  parlai/zoo/fasttext_vectors/__init__.py
  parlai/zoo/fasttext_vectors/build.py
Labels: CLA Signed

#866 Fixes w.r.t. PR comments
  parlai/scripts/eval_wordstat.py
Labels: CLA Signed

#868 Some tuning params for kvmemnn, could be useful..
  projects/personachat/kvmemnn/kvmemnn.py
Labels: CLA Signed

#874 reduce s2s memory usage
  parlai/agents/seq2seq/modules.py
Labels: CLA Signed

#867 [MTurk] Separating block qualifications for disconnects and soft blocks
  docs/source/tutorial_mturk.rst
  parlai/core/params.py
  parlai/mturk/core/mturk_manager.py
Labels: CLA Signed

#877 [MTurk] Fix bug wasn't tracking time blocked workers to free later
  parlai/mturk/core/mturk_manager.py
Labels: CLA Signed

#873 pytorch_teacher dataset loading update
  docs/source/tutorial_worlds.rst
  parlai/core/pytorch_data_teacher.py
Labels: CLA Signed

#878 [Messenger] Fixing message sender splits
  parlai/messenger/core/message_sender.py
Labels: CLA Signed

#872 Squad-fulldoc teacher + generic ParlAIformat
  parlai/core/dict.py
  parlai/core/teachers.py
  parlai/scripts/eval_model.py
  parlai/tasks/fromfile/agents.py
  parlai/tasks/squad/agents.py
  parlai/tasks/squad/build.py
Labels: CLA Signed

#881 Hide metrics
  parlai/core/worlds.py
  parlai/scripts/eval_model.py
  projects/convai2/eval_f1.py
  projects/convai2/eval_hits.py
Labels: CLA Signed

#885 Bug fix for ParlAI Dialog teacher
  parlai/core/teachers.py
Labels: CLA Signed

#884 update override to be dict-only
  parlai/core/agents.py
  parlai/mturk/tasks/convai2_model_eval/run.py
  projects/convai2/baselines/kvmemnn/interactive.py
  projects/personachat/kvmemnn/kvmemnn.py
  projects/personachat/scripts/kvmemnn_interactive.py
Labels: CLA Signed

#886 params automatically changes underscores to hyphens
  parlai/core/params.py
Labels: CLA Signed

#883 update arg for pytorch buildteacher
  docs/source/tutorial_worlds.rst
  parlai/agents/mlb_vqa/mlb_vqa.py
  parlai/core/agents.py
  parlai/core/params.py
  parlai/core/pytorch_data_teacher.py
  parlai/core/teachers.py
  parlai/core/worlds.py
  parlai/scripts/build_dict.py
  parlai/scripts/build_pytorch_data.py
  parlai/scripts/extract_image_feature.py
  tests/test_mlb_vqa.py
Labels: CLA Signed

#889 Update drqa model in model zoo
  parlai/zoo/drqa/squad.py
  projects/drqa/eval_pretrained.py
  projects/drqa/train.py
Labels: CLA Signed

#890 add unit tests to travis
  .travis.yml
Labels: CLA Signed

#892 fix flake and unit errors
  .travis.yml
  parlai/agents/tfidf_retriever/tfidf_retriever.py
  parlai/agents/tfidf_retriever/utils.py
  parlai/core/torch_agent.py
  parlai/core/utils.py
  parlai/scripts/convert_data_to_parlai_format.py
  parlai/scripts/train_model.py
  tests/test_tfidf_retriever.py
  tests/test_torch_agent.py
Labels: CLA Signed

#891 Using more lenient timeouts until disconnects improved
  parlai/mturk/core/server/html/core.html
  parlai/mturk/core/socket_manager.py
Labels: CLA Signed

#895 Fix some bugs in image captioning framework
  parlai/core/teachers.py
  parlai/core/torch_agent.py
  parlai/tasks/coco_caption/agents.py
  parlai/tasks/flickr30k/agents.py
Labels: CLA Signed

#888 Mlb_vqa updates for pytorch 0.4
  parlai/agents/mlb_vqa/dropout.py
  parlai/agents/mlb_vqa/gru.py
  parlai/agents/mlb_vqa/loadstates.py
  parlai/agents/mlb_vqa/mlb_modules.py
  parlai/agents/mlb_vqa/mlb_vqa.py
Labels: CLA Signed

#897 switch ModuleNotFoundError to parent ImportError
  parlai/agents/drqa/drqa.py
  parlai/agents/ibm_seq2seq/ibm_seq2seq.py
  parlai/agents/seq2seq/seq2seq.py
  parlai/agents/tfidf_retriever/tfidf_retriever.py
  parlai/agents/tfidf_retriever/utils.py
  parlai/core/build_data.py
  parlai/core/image_featurizers.py
  parlai/core/logs.py
  parlai/core/pytorch_data_teacher.py
  parlai/core/torch_agent.py
  parlai/core/utils.py
  parlai/messenger/core/__init__.py
  parlai/mturk/core/__init__.py
  parlai/mturk/core/test/auto_complete_hit.py
  parlai/scripts/extract_image_feature.py
  parlai/scripts/profile_train.py
  parlai/tasks/coco_caption/agents.py
  parlai/tasks/flickr30k/agents.py
  parlai/tasks/twitter/build.py
  parlai/tasks/vqa_v1/agents.py
  projects/personachat/persona_seq2seq.py
  tests/test_tfidf_retriever.py
  tests/test_torch_agent.py
Labels: CLA Signed

#899 Fix Issues Raised in #895 and Update Tests
  parlai/core/torch_agent.py
  parlai/tasks/coco_caption/agents.py
  tests/test_torch_agent.py
Labels: CLA Signed

#894 Updates to TorchAgent
  parlai/agents/example_seq2seq/example_seq2seq.py
  parlai/core/torch_agent.py
  tests/test_torch_agent.py
Labels: CLA Signed, agents, bug, enhancement

#900 [MTurk] Fixing time resets
  parlai/mturk/core/mturk_manager.py
Labels: CLA Signed

#898 testing installing torch on travis
  .travis.yml
  parlai/agents/tfidf_retriever/tfidf_retriever.py
Labels: CLA Signed

#902 Update override_opts_in_shared to reduce recursive calls
  parlai/core/worlds.py
  parlai/scripts/build_pytorch_data.py
Labels: CLA Signed

#903 misc updates
  parlai/agents/seq2seq/modules.py
  parlai/agents/seq2seq/seq2seq.py
  parlai/core/dict.py
  parlai/core/params.py
  parlai/core/utils.py
  parlai/scripts/eval_wordstat.py
  projects/convai2/baselines/seq2seq/eval_wordstat.py
Labels: CLA Signed

#896 Wordstat uniqueness calculation
  parlai/core/metrics.py
  parlai/scripts/eval_wordstat.py
Labels: CLA Signed

#908 Attaching quick replies to facebook attachments
  parlai/messenger/core/agents.py
  parlai/messenger/core/message_sender.py
  parlai/messenger/core/messenger_manager.py
Labels: CLA Signed

#909 [Messenger] Adding retries for retriable errors
  parlai/messenger/core/message_sender.py
Labels: CLA Signed

#911 Create Documentation_License
  projects/personachat/Documentation_License
Labels: CLA Signed

#905 TorchAgent needs to actually load the model state it saves.
  parlai/core/torch_agent.py
Labels: CLA Signed

#913 [MTurk] qa-data-collection broken by new task opts
  parlai/mturk/tasks/qa_data_collection/run.py
Labels: CLA Signed

#917 print task and datatype at end of eval
  parlai/scripts/eval_model.py
Labels: CLA Signed

#919 Fix a bug when overriding a CLI option to an intentional blank.
  parlai/core/params.py
Labels: CLA Signed

#920 small parlaiformat issues
  parlai/core/teachers.py
  parlai/core/utils.py
Labels: CLA Signed

#922 Fix bug where START and END tokens were generated by fairseq models.
  parlai/agents/fairseq/fairseq.py
Labels: CLA Signed

#921 refactor messenger_manager to clean up redundancies
  parlai/core/params.py
  parlai/messenger/core/messenger_manager.py
Labels: CLA Signed

#929 fairseq logging rounding
  parlai/agents/fairseq/fairseq.py
Labels: CLA Signed

#931 Add a mark_removed method for MessengerManager
  parlai/messenger/core/messenger_manager.py
Labels: CLA Signed

#926 save attn mask in prevenc
  parlai/agents/seq2seq/modules.py
Labels: CLA Signed

#927 update batchindex setting
  parlai/agents/ibm_seq2seq/ibm_seq2seq.py
  parlai/agents/memnn/memnn.py
  parlai/agents/seq2seq/seq2seq.py
  parlai/core/worlds.py
  projects/mastering_the_dungeon/tasks/graph_world2/agents.py
  projects/personachat/persona_seq2seq.py
Labels: CLA Signed

#934 Moving to new metric for determining disconnects
  parlai/mturk/core/agents.py
  parlai/mturk/core/mturk_manager.py
  parlai/mturk/core/server/html/core.html
  parlai/mturk/core/server/server.js
  parlai/mturk/core/socket_manager.py
Labels: CLA Signed

#935 speed up s2s ~2x
  parlai/agents/seq2seq/seq2seq.py
Labels: CLA Signed

#936 packed assigned to False in except branch
  parlai/agents/seq2seq/modules.py
Labels: CLA Signed

#938 Move display script, add max length arg
  examples/display_data.py
  parlai/core/utils.py
  parlai/core/worlds.py
  parlai/scripts/display_data.py
Labels: CLA Signed
