Repository facebookresearch/ParlAI, pull requests merged in 2018-11, with the labels that each got.

#1262 Beam search fix
  parlai/agents/seq2seq/seq2seq.py
  parlai/core/torch_agent.py
Labels: CLA Signed, agents, torchagent

#1265 Copyright and __init__.py updates.
  parlai/mturk/webapp/dev/main.js
  parlai/mturk/webapp/server.py
  parlai/mturk/webapp/webpack.config.js
  tests/test_code.py
Labels: CLA Signed

#1264 Fix broken flake8 due to upstream upgrade.
  .flake8
  tests/lint_changed.sh
Labels: CLA Signed

#1261 Assignment view with approval features.
  .travis.yml
  parlai/mturk/core/mturk_data_handler.py
  parlai/mturk/core/mturk_manager.py
  parlai/mturk/core/test/test_db_interactions.py
  parlai/mturk/core/test/test_full_system.py
  parlai/mturk/core/test/test_mturk_agent.py
  parlai/mturk/core/test/test_mturk_manager.py
  parlai/mturk/core/test/test_socket_manager.py
  parlai/mturk/core/test/test_worker_manager.py
  parlai/mturk/webapp/.babelrc
  parlai/mturk/webapp/dev/app.jsx
  parlai/mturk/webapp/dev/css/style.css
  parlai/mturk/webapp/dev/main.js
  parlai/mturk/webapp/package.json
  parlai/mturk/webapp/server.py
Labels: CLA Signed, MTurk

#1267 Memoize beam hypos on the way
  parlai/core/torch_agent.py
Labels: CLA Signed

#1268 parlai dialog should return copy of its messages, not the (modifiable) original
  parlai/core/teachers.py
Labels: CLA Signed

#1263 Torchagent flags
  parlai/core/torch_agent.py
Labels: CLA Signed, torchagent

#1273 Revert last commit, which broke pytorch 0.3 backwards compatibility
  parlai/agents/seq2seq/seq2seq.py
Labels: CLA Signed

#1272 add function for retrieving past model replies in episode
  parlai/core/torch_agent.py
Labels: CLA Signed

#1270 Wizard of Wikipedia Task
  NEWS.md
  parlai/tasks/task_list.py
  parlai/tasks/wizard_of_wikipedia/__init__.py
  parlai/tasks/wizard_of_wikipedia/agents.py
  parlai/tasks/wizard_of_wikipedia/build.py
  tests/tasks/test_wizard_of_wikipedia.py
  tests/test_new_tasks.py
Labels: CLA Signed

#1276 change jquery version because of vulnerability
  parlai/mturk/webapp/package.json
Labels: CLA Signed

#1279 Fix the CUDA/Hogwild test_seq2seq bug.
  tests/test_seq2seq.py
Labels: CLA Signed

#1281 React frontend
  MANIFEST.in
  parlai/mturk/core/agents.py
  parlai/mturk/core/mturk_data_handler.py
  parlai/mturk/core/mturk_manager.py
  parlai/mturk/core/react_server/.babelrc
  parlai/mturk/core/react_server/__init__.py
  parlai/mturk/core/react_server/dev/app.jsx
  parlai/mturk/core/react_server/dev/component_deps/package.json
  parlai/mturk/core/react_server/dev/components/custom.jsx
  parlai/mturk/core/react_server/dev/components/mturk_submit_form.jsx
  parlai/mturk/core/react_server/dev/components/socket_handler.jsx
  parlai/mturk/core/react_server/dev/css/custom.css
  parlai/mturk/core/react_server/dev/css/style.css
  parlai/mturk/core/react_server/dev/main.js
  parlai/mturk/core/react_server/package-lock.json
  parlai/mturk/core/react_server/package.json
  parlai/mturk/core/react_server/server/package.json
  parlai/mturk/core/react_server/server/server.js
  parlai/mturk/core/react_server/server/static/index.html
  parlai/mturk/core/react_server/webpack.config.js
  parlai/mturk/core/server_legacy/__init__.py
  parlai/mturk/core/server_legacy/html/core.html
  parlai/mturk/core/server_legacy/html/cover_page.html
  parlai/mturk/core/server_legacy/html/mturk_index.html
  parlai/mturk/core/server_legacy/package.json
  parlai/mturk/core/server_legacy/server.js
  parlai/mturk/core/server_utils.py
  parlai/mturk/core/test/test_full_system.py
  parlai/mturk/core/test/test_mturk_manager.py
  parlai/mturk/tasks/react_task_demo/__init__.py
  parlai/mturk/tasks/react_task_demo/frontend/components/custom.jsx
  parlai/mturk/tasks/react_task_demo/frontend/components/package.json
  parlai/mturk/tasks/react_task_demo/run.py
  parlai/mturk/tasks/react_task_demo/task_config.py
  parlai/mturk/tasks/react_task_demo/worlds.py
Labels: CLA Signed, MTurk, enhancement

#1282 Seq2seq version bump.
  parlai/agents/legacy_agents/seq2seq/dict_v1.py
  parlai/agents/legacy_agents/seq2seq/modules_v1.py
  parlai/agents/legacy_agents/seq2seq/seq2seq_v1.py
  parlai/agents/legacy_agents/seq2seq/torch_agent_v1.py
  parlai/agents/legacy_agents/seq2seq/utils_v1.py
  parlai/agents/seq2seq/seq2seq.py
Labels: CLA Signed

#1287 Workaround for batch mturk bug.
  parlai/core/torch_agent.py
Labels: CLA Signed

#1286 bump query version
  parlai/mturk/core/react_server/dev/component_deps/package.json
  parlai/mturk/core/react_server/package.json
  parlai/mturk/core/react_server/server/static/index.html
  parlai/mturk/core/server_legacy/html/core.html
  parlai/mturk/tasks/react_task_demo/frontend/components/package.json
Labels: CLA Signed

#1288 Additional test labels for Personality-Captions
  parlai/tasks/personality_captions/agents.py
  parlai/tasks/personality_captions/build.py
Labels: CLA Signed

#1289 Personality Captions MTurk Task
  parlai/mturk/tasks/personality_captions/personality_captions/__init__.py
  parlai/mturk/tasks/personality_captions/personality_captions/html/Commenter_index.html
  parlai/mturk/tasks/personality_captions/personality_captions/html/cover_page.html
  parlai/mturk/tasks/personality_captions/personality_captions/html/onboarding_index.html
  parlai/mturk/tasks/personality_captions/personality_captions/personality_and_image_idx_stack_sandbox.pkl
  parlai/mturk/tasks/personality_captions/personality_captions/run.py
  parlai/mturk/tasks/personality_captions/personality_captions/task_configs/task_config_caption.py
  parlai/mturk/tasks/personality_captions/personality_captions/task_configs/task_config_no_personality.py
  parlai/mturk/tasks/personality_captions/personality_captions/task_configs/task_config_personality.py
  parlai/mturk/tasks/personality_captions/personality_captions/worlds.py
Labels: CLA Signed

#1294 change default value of empty observation to {} from None
  parlai/core/torch_agent.py
Labels: CLA Signed

#1290 Wizard of Wikipedia MTurk Task
  parlai/mturk/tasks/wizard_of_wikipedia/constants.py
  parlai/mturk/tasks/wizard_of_wikipedia/extract_and_save_personas.py
  parlai/mturk/tasks/wizard_of_wikipedia/html/Apprentice_index.html
  parlai/mturk/tasks/wizard_of_wikipedia/html/Wizard_index.html
  parlai/mturk/tasks/wizard_of_wikipedia/html/cover_page.html
  parlai/mturk/tasks/wizard_of_wikipedia/html/onboarding_index.html
  parlai/mturk/tasks/wizard_of_wikipedia/run.py
  parlai/mturk/tasks/wizard_of_wikipedia/task_config.py
  parlai/mturk/tasks/wizard_of_wikipedia/worlds.py
Labels: CLA Signed

#1291 Image Chat MTurk task
  parlai/mturk/tasks/image_chat/image_chat_collection/__init__.py
  parlai/mturk/tasks/image_chat/image_chat_collection/html/Responder_index.html
  parlai/mturk/tasks/image_chat/image_chat_collection/html/cover_page.html
  parlai/mturk/tasks/image_chat/image_chat_collection/html/onboarding_index.html
  parlai/mturk/tasks/image_chat/image_chat_collection/run.py
  parlai/mturk/tasks/image_chat/image_chat_collection/task_configs/task_config_first_response.py
  parlai/mturk/tasks/image_chat/image_chat_collection/task_configs/task_config_second_response.py
  parlai/mturk/tasks/image_chat/image_chat_collection/worlds.py
Labels: CLA Signed

#1210 Deprecate FDT Batch Sort in favor of PDT Batch Sort (on the fly)
  docs/source/tutorial_seq2seq.rst
  docs/source/tutorial_worlds.rst
  parlai/agents/tfidf_retriever/tfidf_retriever.py
  parlai/core/params.py
  parlai/core/pytorch_data_teacher.py
  parlai/core/teachers.py
  parlai/core/utils.py
  parlai/scripts/build_pytorch_data.py
Labels: CLA Signed

#1283 Transformer Ranker & Generator
  .travis.yml
  parlai/agents/transformer/__init__.py
  parlai/agents/transformer/generator.py
  parlai/agents/transformer/modules.py
  parlai/agents/transformer/ranker.py
  parlai/agents/transformer/transformer.py
  parlai/core/torch_generator_agent.py
  parlai/core/torch_ranker_agent.py
  tests/integration/test_transformers.py
Labels: CLA Signed

#1295 Random index while streaming PytorchDataTeacher
  parlai/core/pytorch_data_teacher.py
  parlai/scripts/build_pytorch_data.py
  tests/test_pytorch_data_teacher.py
Labels: CLA Signed

#1296 add interactive ranking mode for humans
  parlai/core/metrics.py
  parlai/scripts/interactive.py
  parlai/scripts/interactive_rank.py
Labels: CLA Signed

#1298 [MTurk] Making notification sound on COMMAND_SEND_MESSAGE
  parlai/mturk/core/react_server/dev/app.jsx
  parlai/mturk/core/react_server/dev/components/core_components.jsx
  parlai/mturk/core/react_server/dev/components/socket_handler.jsx
  parlai/mturk/core/react_server/package-lock.json
  parlai/mturk/core/react_server/package.json
  parlai/mturk/core/react_server/server/static/index.html
  parlai/mturk/core/react_server/server/static/notif.mp3
  parlai/mturk/tasks/react_task_demo/react_custom_no_extra_deps/frontend/components/custom.jsx
  parlai/mturk/tasks/react_task_demo/react_custom_with_deps/frontend/components/custom.jsx
Labels: CLA Signed

#1299 View custom components in review frontend
  .gitignore
  parlai/mturk/core/react_server/dev/components/core_components.jsx
  parlai/mturk/tasks/react_task_demo/react_custom_with_deps/frontend/package.json
  parlai/mturk/webapp/.babelrc
  parlai/mturk/webapp/.gitignore
  parlai/mturk/webapp/dev/app.jsx
  parlai/mturk/webapp/package.json
  parlai/mturk/webapp/server.py
  parlai/mturk/webapp/static/index.html
  parlai/mturk/webapp/webpack.config.js
Labels: CLA Signed, MTurk

#1300 Personality Captions Human Eval Task
  parlai/mturk/tasks/personality_captions/stack_rank_evals/__init__.py
  parlai/mturk/tasks/personality_captions/stack_rank_evals/html/Chooser_index.html
  parlai/mturk/tasks/personality_captions/stack_rank_evals/html/cover_page.html
  parlai/mturk/tasks/personality_captions/stack_rank_evals/html/onboarding_index.html
  parlai/mturk/tasks/personality_captions/stack_rank_evals/run.py
  parlai/mturk/tasks/personality_captions/stack_rank_evals/task_config.py
  parlai/mturk/tasks/personality_captions/stack_rank_evals/worlds.py
Labels: CLA Signed
