Repository facebookresearch/ParlAI, pull requests merged in 2019-07, with the labels that each got.

#1810 Interactive worlds
  parlai/agents/local_human/local_human.py
  parlai/core/agents.py
  parlai/core/torch_ranker_agent.py
  parlai/core/worlds.py
  parlai/scripts/interactive.py
  parlai/tasks/convai2/agents.py
  parlai/tasks/convai2/worlds.py
  parlai/tasks/interactive/README.md
  parlai/tasks/interactive/__init__.py
  parlai/tasks/interactive/agents.py
  parlai/tasks/interactive/worlds.py
  tests/test_zootasks.py
Labels: CLA Signed

#1822 Add twitter feed to the website.
  website/static/css/parlai.css
  website/templates/home.html
Labels: CLA Signed

#1823 Fix 'see examples' button.
  website/templates/home.html
Labels: CLA Signed

#1825 `url-loader` for svg/png/jpe/jpeg/ttf
  parlai/mturk/core/react_server/webpack.config.js
Labels: CLA Signed

#1824 Install `url-loader` into react_server.
  parlai/mturk/core/react_server/package.json
Labels: CLA Signed

#1821 Fix clevr download link.
  parlai/tasks/clevr/build.py
Labels: CLA Signed

#1818 [MTurk] Disconnects raise instead of silently text failing
  parlai/mturk/core/dev/agents.py
  parlai/mturk/core/dev/mturk_manager.py
  parlai/mturk/core/dev/react_server/server/server.js
  parlai/mturk/core/dev/worlds.py
Labels: CLA Signed

#1758 Add example parlai internal folder
  docs/source/tutorial_quick.rst
  docs/source/tutorial_tipsntricks.rst
  example_parlai_internal/README.md
  example_parlai_internal/__init__.py
  example_parlai_internal/agents/parrot/parrot.py
  example_parlai_internal/zoo/.internal_zoo_path
  parlai_internal_test/README.md
  parlai_internal_test/__init__.py
  parlai_internal_test/agents/parrot/parrot.py
  parlai_internal_test/example_parlai_internal/README.md
  parlai_internal_test/example_parlai_internal/__init__.py
  parlai_internal_test/example_parlai_internal/agents/parrot/parrot.py
  parlai_internal_test/example_parlai_internal/zoo/.internal_zoo_path
  parlai_internal_test/zoo/.internal_zoo_path
Labels: CLA Signed

#1827 personality-captions website: add parlai quickstart link
  projects/personality_captions/README.md
Labels: CLA Signed

#1809 Add support for Resnext101 WSL features
  parlai/core/image_featurizers.py
  parlai/scripts/extract_image_feature.py
Labels: CLA Signed

#1783 Transresnet Multimodal Release
  parlai/tasks/image_chat/agents.py
  parlai/zoo/image_chat/__init__.py
  parlai/zoo/image_chat/transresnet_multimodal.py
  parlai/zoo/model_list.py
  projects/image_chat/Examples.png
  projects/image_chat/README.md
  projects/image_chat/interactive.py
  projects/image_chat/transresnet_multimodal/__init__.py
  projects/image_chat/transresnet_multimodal/modules.py
  projects/image_chat/transresnet_multimodal/transresnet_multimodal.py
  tests/nightly/gpu/test_transresnet_multimodal.py
Labels: CLA Signed

#1829 Ubuntu v2, other small task doc updates
  parlai/tasks/empathetic_dialogues/README.md
  parlai/tasks/hotpotqa/README.md
  parlai/tasks/task_list.py
  parlai/tasks/ubuntu/README.md
Labels: CLA Signed

#1828 Added multi-turn teacher for Ubuntu task
  parlai/tasks/ubuntu/agents.py
Labels: CLA Signed

#1834 [transformer] Raise the layer norm epsilon
  parlai/agents/transformer/modules.py
Labels: CLA Signed

#1832 [Wizard of Wikipedia] add interactive world
  parlai/tasks/wizard_of_wikipedia/agents.py
  parlai/tasks/wizard_of_wikipedia/worlds.py
  projects/wizard_of_wikipedia/interactive_retrieval/interactive_retrieval.py
  projects/wizard_of_wikipedia/scripts/interactive_retrieval_model.py
  projects/wizard_of_wikipedia/wizard_transformer_ranker/wizard_transformer_ranker.py
Labels: CLA Signed

#1836 Don't round_sigfigs num_updates in distributed mode.
  parlai/scripts/train_model.py
Labels: CLA Signed

#1835 Add weight decay.
  parlai/core/params.py
  parlai/core/torch_agent.py
Labels: CLA Signed

#1833 Divide the loss by update_freq when using gradient accumulation.
  parlai/core/torch_agent.py
Labels: CLA Signed

#1842 [WoW] Fix sharing for retrieval interactive agent.
  projects/wizard_of_wikipedia/interactive_retrieval/interactive_retrieval.py
Labels: CLA Signed

#1748 New readme
  README.md
  parlai/core/README.md
Labels: CLA Signed

#1844 top level README: small updates
  README.md
Labels: CLA Signed

#1845 Drop transformer beta warning.
  parlai/agents/transformer/transformer.py
Labels: CLA Signed

#1615 Delete IBM seq2seq.
  NEWS.md
  docs/requirements.txt
  parlai/agents/ibm_seq2seq/__init__.py
  parlai/agents/ibm_seq2seq/ibm_seq2seq.py
  tests/lint_changed.sh
Labels: CLA Signed

#1841 Option for lenient argparser
  parlai/core/params.py
Labels: CLA Signed

#1847 Pretrained transformers
  parlai/core/torch_ranker_agent.py
  parlai/zoo/model_list.py
  parlai/zoo/pretrained_transformers/README.md
  parlai/zoo/pretrained_transformers/bi_model_huge_reddit.py
  parlai/zoo/pretrained_transformers/bi_model_huge_wikito.py
  parlai/zoo/pretrained_transformers/build.py
  parlai/zoo/pretrained_transformers/cross_model_huge_reddit.py
  parlai/zoo/pretrained_transformers/cross_model_huge_wikito.py
  parlai/zoo/pretrained_transformers/model_bi.py
  parlai/zoo/pretrained_transformers/model_poly.py
  parlai/zoo/pretrained_transformers/poly_model_huge_reddit.py
  parlai/zoo/pretrained_transformers/poly_model_huge_wikito.py
Labels: CLA Signed

#1848 Fix empathetic dialogue description in task list.
  parlai/tasks/task_list.py
Labels: CLA Signed

#1849 [WoW] Doc reader teacher bug
  parlai/tasks/wizard_of_wikipedia/agents.py
Labels: CLA Signed

#1846 Fix distributed initialization of model copies.
  .circleci/config.yml
  .circleci/triggers.py
  parlai/core/distributed_utils.py
  parlai/core/torch_generator_agent.py
  parlai/scripts/multiprocessing_train.py
  setup.py
  tests/test_distributed.py
  tests/test_pytorch_data_teacher.py
  tests/test_threadutils.py
Labels: CLA Signed, distributed

#1851 Zoo, Doc improvements
  docs/source/generate_zoo_list.py
  docs/source/zoo.rst
  parlai/zoo/model_list.py
  projects/README.md
  projects/wizard_of_wikipedia/README.md
Labels: CLA Signed

#1853 convai2 interactive: episode didn't end bug
  parlai/core/torch_ranker_agent.py
  parlai/tasks/convai2/worlds.py
Labels: CLA Signed

#1854 Add better examples for self feeding. Fix a compile error.
  docs/source/generate_zoo_list.py
  parlai/tasks/task_list.py
  parlai/zoo/model_list.py
  projects/self_feeding/README.md
Labels: CLA Signed

#1857 Fix CircleCI nightly typo.
  .circleci/config.yml
Labels: CLA Signed

#1852 [MTurk] Better hit status tracking via complete post
  parlai/mturk/core/dev/agents.py
  parlai/mturk/core/dev/data_model.py
  parlai/mturk/core/dev/mturk_manager.py
  parlai/mturk/core/dev/react_server/dev/app.jsx
  parlai/mturk/core/dev/react_server/dev/components/mturk_submit_form.jsx
  parlai/mturk/core/dev/react_server/package.json
  parlai/mturk/core/dev/react_server/server/server.js
  parlai/mturk/core/dev/react_server/webpack.config.js
  parlai/mturk/core/dev/socket_manager.py
  parlai/mturk/core/dev/worker_manager.py
  parlai/mturk/core/dev/worlds.py
Labels: CLA Signed, MTurk

#1838 Report gradient norm and clipping statistics
  parlai/core/torch_agent.py
  parlai/core/torch_classifier_agent.py
  parlai/core/torch_generator_agent.py
  parlai/core/torch_ranker_agent.py
Labels: CLA Signed

#1860 Downgrade docutils
  requirements.txt
Labels: CLA Signed

#1859 Support setting adam epsilon.
  parlai/core/torch_agent.py
  tests/test_transformers.py
Labels: CLA Signed

#1862 Bug fixes in true distributed.
  parlai/core/torch_generator_agent.py
  parlai/scripts/distributed_train.py
  parlai/scripts/multiprocessing_train.py
Labels: CLA Signed

#1858 Flaky test fix.
  tests/nightly/gpu/test_convai2.py
Labels: CLA Signed

#1806 Add upgrade_opt support.
  parlai/agents/bert_classifier/bert_classifier.py
  parlai/core/agents.py
  parlai/core/params.py
  parlai/core/torch_agent.py
  tests/test_params.py
Labels: CLA Signed

#1850 Added DSTC7 and ubuntu teachers
  parlai/scripts/verify_data.py
  parlai/tasks/dstc7/__init__.py
  parlai/tasks/dstc7/agents.py
  parlai/tasks/task_list.py
  parlai/tasks/ubuntu/agents.py
  tests/datatests/test_new_tasks.py
Labels: CLA Signed

#1866 VQA V1 teacher fix
  parlai/tasks/vqa_v1/agents.py
Labels: CLA Signed

#1865 Remove some older agents; slight reorgs
  parlai/agents/README.md
  parlai/agents/legacy_agents/memnn_luatorch_cpu/__init__.py
  parlai/agents/legacy_agents/memnn_luatorch_cpu/examples/__init__.py
  parlai/agents/legacy_agents/memnn_luatorch_cpu/examples/full_task_train.py
  parlai/agents/legacy_agents/memnn_luatorch_cpu/examples/params_default.lua
  parlai/agents/legacy_agents/memnn_luatorch_cpu/memnn_agent.lua
  parlai/agents/legacy_agents/memnn_luatorch_cpu/memnn_agent_parsed.lua
  parlai/agents/legacy_agents/memnn_luatorch_cpu/memnn_zmq.lua
  parlai/agents/legacy_agents/memnn_luatorch_cpu/memnn_zmq_parsed.lua
  parlai/agents/mlb_vqa/README.md
  parlai/agents/mlb_vqa/__init__.py
  parlai/agents/mlb_vqa/dropout.py
  parlai/agents/mlb_vqa/gru.py
  parlai/agents/mlb_vqa/loadstates.py
  parlai/agents/mlb_vqa/mlb_modules.py
  parlai/agents/mlb_vqa/mlb_vqa.py
  parlai/agents/vsepp_caption/README.md
  parlai/agents/vsepp_caption/__init__.py
  parlai/agents/vsepp_caption/modules.py
  parlai/agents/vsepp_caption/vsepp_caption.py
  parlai/tasks/vqa_v1/agents.py
  parlai_internal_test/README.md
  parlai_internal_test/__init__.py
  parlai_internal_test/agents/parrot/parrot.py
  parlai_internal_test/example_parlai_internal/README.md
  parlai_internal_test/example_parlai_internal/__init__.py
  parlai_internal_test/example_parlai_internal/agents/parrot/parrot.py
  parlai_internal_test/example_parlai_internal/zoo/.internal_zoo_path
  parlai_internal_test/zoo/.internal_zoo_path
  projects/taskntalk/README.rst
  projects/taskntalk/__init__.py
  projects/taskntalk/coopgame_agent.py
  projects/taskntalk/modules.py
  projects/taskntalk/taskntalk.png
Labels: CLA Signed

#1868 Build history
  parlai/core/torch_agent.py
Labels: CLA Signed

#1864 Animal Control: Enforce quality constraints in zoo
  parlai/zoo/model_list.py
  parlai/zoo/twitter/__init__.py
  parlai/zoo/twitter/dict.py
  parlai/zoo/twitter/seq2seq.py
  projects/polyencoder/README.md
  tests/test_zootasks.py
Labels: CLA Signed

#1870 OS X unit testing.
  .circleci/config.yml
Labels: CLA Signed

#1871 Call upgrade_opt before local CLI overrides occur
  parlai/core/agents.py
Labels: CLA Signed

#1869 Add episode done to interactive_web.
  parlai/scripts/interactive_web.py
Labels: CLA Signed

#1856 Explicit metric shortcutting with --metrics
  parlai/core/metrics.py
  parlai/core/worlds.py
  parlai/scripts/eval_model.py
  parlai/scripts/train_model.py
  tests/test_eval_model.py
Labels: CLA Signed
