Repository facebookresearch/ParlAI, pull requests merged in 2019-06, with the labels that each got.

#1734 Release remaining Controllable Dialogue Code
  projects/controllable_dialogue/Analysis_n_Graphs.ipynb
  projects/controllable_dialogue/README.md
  projects/controllable_dialogue/controllable_seq2seq/controllable_seq2seq.py
  projects/controllable_dialogue/mturk/__init__.py
  projects/controllable_dialogue/mturk/html/PERSON_1_index.html
  projects/controllable_dialogue/mturk/html/PERSON_2_index.html
  projects/controllable_dialogue/mturk/html/onboarding_index.html
  projects/controllable_dialogue/mturk/model_configs.py
  projects/controllable_dialogue/mturk/run.py
  projects/controllable_dialogue/mturk/task_config.py
  projects/controllable_dialogue/mturk/worlds.py
  projects/controllable_dialogue/tasks/build.py
Labels: CLA Signed, Release

#1735 Internal Zoo shortcuts
  docs/source/tutorial_basic.rst
  docs/source/tutorial_messenger.rst
  parlai/agents/drqa/drqa.py
  parlai/agents/tfidf_retriever/README.md
  parlai/core/build_data.py
  parlai/core/params.py
  parlai/core/torch_agent.py
  tests/nightly/gpu/test_controllable.py
  tests/nightly/gpu/test_drqa.py
  tests/nightly/gpu/test_wizard.py
  tests/test_dict.py
  tests/test_seq2seq.py
  tests/test_transformers.py
Labels: CLA Signed

#1717 Add warning when positions exceeds embedding matrix size
  parlai/agents/transformer/modules.py
Labels: CLA Signed

#1738 [Torch Ranker Agent] Hard reset LR if finetune
  parlai/core/torch_ranker_agent.py
  tests/test_transformers.py
Labels: CLA Signed

#1740 Fix fp16 candidate encodings.
  parlai/core/torch_agent.py
  parlai/core/torch_ranker_agent.py
Labels: CLA Signed

#1741 new update: coqa and quac
  NEWS.md
Labels: CLA Signed

#1736 Add docstring linting to ParlAI
  .circleci/triggers.py
  .flake8
  parlai/core/__init__.py
  parlai/core/agents.py
  parlai/core/build_data.py
  parlai/core/dict.py
  parlai/core/distributed_utils.py
  parlai/core/logs.py
  parlai/core/metrics.py
  parlai/core/params.py
  parlai/core/pytorch_data_teacher.py
  parlai/core/teachers.py
  parlai/core/testing_utils.py
  parlai/core/thread_utils.py
  parlai/core/torch_agent.py
  parlai/core/torch_classifier_agent.py
  parlai/core/torch_generator_agent.py
  parlai/core/torch_ranker_agent.py
  parlai/core/utils.py
  parlai/core/worlds.py
  requirements.txt
Labels: CLA Signed, docs

#1745 Lint image featurizer.
  parlai/core/image_featurizers.py
Labels: CLA Signed

#1744 Training script docstrings
  parlai/scripts/train_model.py
Labels: CLA Signed

#1757 task flags tip
  docs/source/tutorial_tipsntricks.rst
  parlai/core/agents.py
Labels: CLA Signed

#1751 Update pull_request_template.md
  .github/pull_request_template.md
Labels: CLA Signed, bug, docs

#1746 Multitask training loss reporting temp fix + better multitasks task names from task IDs
  parlai/core/worlds.py
  parlai/scripts/train_model.py
Labels: CLA Signed

#1755 [docs] README - Add additional badges in the header
  README.md
Labels: CLA Signed

#1761 Arg provenance: trace your opt history
  parlai/core/agents.py
  parlai/core/params.py
  parlai/core/utils.py
  tests/test_utils.py
Labels: CLA Signed

#1760 [MTurk] Fixing socket manager test
  parlai/mturk/core/test/test_socket_manager.py
Labels: CLA Signed

#1753 ABCs for TA, TRA, & TGA
  parlai/agents/memnn/memnn.py
  parlai/agents/memnn/modules.py
  parlai/core/torch_agent.py
  parlai/core/torch_generator_agent.py
  parlai/core/torch_ranker_agent.py
Labels: CLA Signed

#1763 Torch Ranker Agent docstrings
  parlai/core/torch_ranker_agent.py
Labels: CLA Signed

#1765 Opt: track deepcopies
  parlai/core/utils.py
Labels: CLA Signed

#1762 Suggestion to check ssl on connection refused
  parlai/mturk/core/dev/socket_manager.py
  parlai/mturk/core/legacy_2018/socket_manager.py
  parlai/mturk/core/socket_manager.py
Labels: CLA Signed

#1768 Allow zoo: paths in --init-model.
  parlai/core/agents.py
Labels: CLA Signed

#1770 Don't output the LR warning when finetuning.
  parlai/core/torch_agent.py
Labels: CLA Signed

#1767 Report number of parameters in TorchAgent.
  parlai/core/torch_agent.py
  parlai/core/torch_generator_agent.py
Labels: CLA Signed

#1772 Address subtleties in fp16/fp32 checkpoint loading
  parlai/core/torch_agent.py
Labels: CLA Signed

#1749 Fix Arg Failure/Error Message
  parlai/core/params.py
Labels: CLA Signed

#1719 add rouge metrics
  .circleci/config.yml
  parlai/core/metrics.py
  requirements.txt
  tests/test_eval_model.py
Labels: CLA Signed

#1764 [Torch Agent] get rid of unused functions
  parlai/core/torch_agent.py
Labels: CLA Signed

#1743 [Torch Agent] break if 'episode_done' key doesn't exist
  parlai/core/torch_agent.py
  tests/test_torch_agent.py
Labels: CLA Signed

#1742 [BERT Classifier] CLS + SEP tokens, plus segments
  parlai/agents/bert_classifier/bert_classifier.py
  parlai/agents/bert_ranker/bert_dictionary.py
Labels: CLA Signed

#1752 HotpotQA task added
  parlai/tasks/hotpotqa/__init__.py
  parlai/tasks/hotpotqa/agents.py
  parlai/tasks/hotpotqa/build.py
  parlai/tasks/task_list.py
Labels: CLA Signed

#1777 remove ambiguity between readmes for empathetic_dialogues
  parlai/tasks/empathetic_dialogues/README.md
  parlai/tasks/empathetic_dialogues/readme.md
Labels: CLA Signed

#1779 Update NEWS.md
  NEWS.md
Labels: CLA Signed

#1729 Add Python3.5 testing.
  .circleci/config.yml
  parlai/agents/transformer/modules.py
  parlai/scripts/profile_train.py
  tests/test_torch_agent.py
Labels: CLA Signed

#1726 Transresnet Model Release
  NEWS.md
  parlai/core/image_featurizers.py
  parlai/core/testing_utils.py
  parlai/tasks/personality_captions/agents.py
  parlai/zoo/model_list.py
  parlai/zoo/personality_captions/__init__.py
  parlai/zoo/personality_captions/transresnet.py
  projects/personality_captions/README.md
  projects/personality_captions/interactive.py
  projects/personality_captions/transresnet/__init__.py
  projects/personality_captions/transresnet/modules.py
  projects/personality_captions/transresnet/transresnet.py
  tests/nightly/gpu/test_transresnet.py
Labels: CLA Signed

#1782 Update NEWS.md
  NEWS.md
Labels: CLA Signed

#1780 TRA heuristic repeats from conversation blocking
  parlai/core/torch_agent.py
  parlai/core/torch_ranker_agent.py
Labels: CLA Signed

#1784 More TRA fixes
  parlai/core/torch_ranker_agent.py
Labels: CLA Signed

#1786 changes to work with CI in parlai internal
  tests/lint_changed.sh
  tests/suites.py
Labels: CLA Signed

#1775 Report correct agent-reported metrics during evaluation when multi-tasking
  parlai/core/metrics.py
  parlai/scripts/eval_model.py
  parlai/scripts/train_model.py
  projects/convai2/baselines/kvmemnn/eval_f1.py
  tests/test_eval_model.py
  tests/test_train_model.py
Labels: CLA Signed

#1731 Quick start and Basic Documentation modifications
  docs/source/tutorial_basic.rst
  docs/source/tutorial_quick.rst
Labels: CLA Signed

#1774 Support using APEX layernorm.
  parlai/agents/transformer/modules.py
Labels: CLA Signed

#1793 [Opt] add ability to pickle this object
  parlai/core/utils.py
Labels: CLA Signed

#1790 Separate embedding memnet
  parlai/agents/transformer/modules.py
  parlai/agents/transformer/transformer.py
Labels: CLA Signed

#1800 Autoformat agents.py and params.py
  .flake8
  parlai/core/agents.py
  parlai/core/params.py
Labels: CLA Signed

#1797 Officially remove py35 support
  .circleci/config.yml
  README.md
  setup.py
Labels: CLA Signed

#1799 loading opts from a json file
  parlai/agents/bert_classifier/bert_classifier.py
  parlai/core/agents.py
  parlai/core/params.py
  parlai/core/utils.py
Labels: CLA Signed

#1801 Add Black support
  .circleci/config.yml
  .flake8
  .pre-commit-config.yaml
  CONTRIBUTING.md
  parlai/core/torch_agent.py
  parlai/core/utils.py
  pyproject.toml
  requirements.txt
  tests/lint_changed.sh
Labels: CLA Signed

#1798 Bug in the qualification_flow_example.py
  parlai/mturk/tasks/qualification_flow_example/worlds.py
Labels: CLA Signed

#1791 Bi, Poly and Cross encoder not dependent from Hugging Face code
  parlai/agents/transformer/biencoder.py
  parlai/agents/transformer/crossencoder.py
  parlai/agents/transformer/modules.py
  parlai/agents/transformer/polyencoder.py
  parlai/agents/transformer/transformer.py
  parlai/core/build_data.py
  parlai/core/torch_agent.py
  parlai/core/torch_ranker_agent.py
  parlai/zoo/model_list.py
  parlai/zoo/pretrained_transformers/README.md
  parlai/zoo/pretrained_transformers/__init__.py
  parlai/zoo/pretrained_transformers/build.py
Labels: CLA Signed

#1796 minor fix for aggregate_task_reports
  parlai/core/metrics.py
Labels: CLA Signed

#1776 Parallelize tests on CircleCI.
  .circleci/config.yml
  tests/suites.py
Labels: CLA Signed

#1807 [Metrics] change default aggregation
  parlai/core/metrics.py
  parlai/scripts/eval_model.py
  parlai/scripts/train_model.py
Labels: CLA Signed

#1803 [MTurk] Agent state change refactor
  parlai/mturk/core/dev/agents.py
  parlai/mturk/core/dev/mturk_manager.py
  parlai/mturk/core/dev/react_server/dev/app.jsx
  parlai/mturk/core/dev/react_server/server/constants/agent_states.js
  parlai/mturk/core/dev/react_server/server/constants/status_messages.js
  parlai/mturk/core/dev/react_server/server/package.json
  parlai/mturk/core/dev/react_server/server/server.js
  parlai/mturk/core/dev/socket_manager.py
  parlai/mturk/core/dev/worker_manager.py
Labels: CLA Signed

#1811 [TA] sharing model
  parlai/core/torch_agent.py
  parlai/core/torch_generator_agent.py
  parlai/core/torch_ranker_agent.py
Labels: CLA Signed

#1808 [Train Loop] kill it faster
  parlai/core/worlds.py
  parlai/scripts/train_model.py
Labels: CLA Signed

#1812 Fix a bug in resuming LR with warmup and reduceonplateau
  parlai/core/torch_agent.py
  tests/test_transformers.py
Labels: CLA Signed

#1813 Beat The Bot project page
  projects/beat_the_bot/README.md
  projects/beat_the_bot/beatthebot.gif
  projects/beat_the_bot/bot.png
Labels: CLA Signed

#1816 Change quickstart tutorial to use `-bs 1` instead
  docs/source/tutorial_quick.rst
Labels: CLA Signed

#1817 [Pretrained transformers] small fix; only save once
  parlai/zoo/pretrained_transformers/build.py
Labels: CLA Signed

#1819 Fix QAngaroo bug
  parlai/tasks/qangaroo/agents.py
Labels: CLA Signed
