Repository facebookresearch/ParlAI, pull requests merged in 2019-10, with the labels that each got.

#2031 [Polyencoders] Fix dict file in READMEs
  parlai/zoo/pretrained_transformers/README.md
  projects/polyencoder/README.md
Labels: CLA Signed

#2034 Small cleanups in train_model.py
  parlai/scripts/train_model.py
Labels: CLA Signed

#2038 Add basic nltk requirement.
  requirements.txt
Labels: CLA Signed

#2032 Function for accessing task agent in world
  parlai/core/worlds.py
  parlai/scripts/build_pytorch_data.py
  parlai/scripts/train_model.py
Labels: CLA Signed

#1998 Added dataset for MultiWOZ
  parlai/tasks/multiwoz/__init__.py
  parlai/tasks/multiwoz/agents.py
  parlai/tasks/multiwoz/build.py
  parlai/tasks/task_list.py
Labels: CLA Signed

#2047 [TGA][fix] beam search producing same hypotheses
  parlai/core/torch_generator_agent.py
Labels: CLA Signed

#2037 Ensure legacy versions raise appropriate error.
  parlai/core/agents.py
  parlai/core/testing_utils.py
  tests/test_torch_agent.py
Labels: CLA Signed

#2050 Quiet false interactive mode warning.
  parlai/core/torch_agent.py
Labels: CLA Signed

#2035 Implement conversation rendering
  parlai/scripts/convo_render.py
Labels: CLA Signed, CS5152, Feature

#2030 Implement Logging
  examples/base_train.py
  examples/remote.py
  parlai/agents/drqa/model.py
  parlai/agents/tfidf_retriever/build_db.py
  parlai/agents/tfidf_retriever/build_tfidf.py
  parlai/agents/tfidf_retriever/tfidf_doc_ranker.py
  parlai/agents/tfidf_retriever/tokenizers/regexp_tokenizer.py
  parlai/agents/tfidf_retriever/tokenizers/simple_tokenizer.py
  parlai/core/distributed_utils.py
  parlai/core/logging_utils.py
  parlai/core/testing_utils.py
  projects/controllable_dialogue/mturk/run.py
  projects/wizard_of_wikipedia/mturk_evaluation_task/run.py
  tests/datatests/test_new_tasks.py
Labels: CLA Signed, CS5152

#2052 Detect bad imports with the linter.
  .flake8
Labels: CLA Signed

#2051 Fix internal CI blacking.
  tests/lint_changed.sh
Labels: CLA Signed

#1949 Bert cross fix
  parlai/agents/bert_ranker/cross_encoder_ranker.py
  parlai/agents/transformer/crossencoder.py
Labels: CLA Signed

#2053 Fix interactive end2end wizard of wikipedia
  projects/wizard_of_wikipedia/interactive_end2end/interactive_end2end.py
Labels: CLA Signed

#1964 Add AbstractImageTeacher and multiprocess downloader
  parlai/core/build_data.py
  parlai/core/teachers.py
Labels: CLA Signed

#2049 GPT-2 tokenizer
  parlai/core/dict.py
  parlai/core/gpt2_helper.py
  tests/test_dict.py
Labels: CLA Signed

#2059 Enhance conversation renderring
  parlai/scripts/convo_render.py
Labels: CLA Signed, CS5152

#2069 Bad inputs for vec2txt for GPT-2 dictionary.
  parlai/core/dict.py
  tests/test_dict.py
Labels: CLA Signed

#2033 Add new unittests for Quickstart docs
  .circleci/config.yml
  docs/source/tutorial_quick.rst
  requirements.txt
  tests/test_quickstart.sh
Labels: CLA Signed

#2072 [TA] rename num_updates report key to total_train_updates.
  parlai/core/torch_agent.py
  parlai/zoo/model_list.py
  tests/test_transformers.py
Labels: CLA Signed

#2065 [Messenger] Update External Messenger Implementation
  docs/source/tutorial_messenger.rst
  parlai/core/params.py
  parlai/messenger/core/messenger_manager.py
  parlai/messenger/core/run.py
  parlai/messenger/core/shared_utils.py
  parlai/messenger/core/world_runner.py
  parlai/messenger/core/worlds.py
  parlai/messenger/tasks/chatbot/config.yml
  parlai/messenger/tasks/chatbot/run.py
  parlai/messenger/tasks/chatbot/worlds.py
  parlai/messenger/tasks/overworld_demo/config.yml
  parlai/messenger/tasks/overworld_demo/run.py
  parlai/messenger/tasks/overworld_demo/worlds.py
  parlai/messenger/tasks/qa_data_collection/config.yml
  parlai/messenger/tasks/qa_data_collection/run.py
  parlai/messenger/tasks/qa_data_collection/worlds.py
Labels: CLA Signed

#2076 Suppress verbose tests and Make minor nits
  parlai/agents/tfidf_retriever/build_db.py
  parlai/agents/tfidf_retriever/build_tfidf.py
  parlai/utils/distributed.py
  parlai/utils/logging.py
  parlai/utils/testing.py
  tests/test_dict.py
  tests/test_tfidf_retriever.py
  tests/test_torch_agent.py
Labels: CLA Signed

#2068 Escape emoji.
  tests/test_dict.py
Labels: CLA Signed

#2056 Backwards compatibility test for MemNN (#1881)
  parlai/utils/testing.py
  tests/test_memnn.py
Labels: CLA Signed

#2055 [WIP] Share the TF-IDF doc ranker
  parlai/agents/tfidf_retriever/tfidf_retriever.py
Labels: CLA Signed

#2083 [Bug] ABC Image Teacher Fix
  parlai/core/teachers.py
  parlai/tasks/integration_tests/agents.py
  tests/test_teachers.py
Labels: CLA Signed

#2084 Remove Create Agent tutorial and all references
  docs/source/index.rst
  docs/source/tutorial_basic.rst
  docs/source/tutorial_seq2seq.rst
  parlai/agents/example_seq2seq/README.md
  parlai/agents/example_seq2seq/__init__.py
  parlai/agents/example_seq2seq/example_seq2seq.py
Labels: CLA Signed

#2085 Update NVIDIA drivers
  .circleci/config.yml
Labels: CLA Signed

#2078 Add versions to requirements and Implement dependency caching
  .circleci/config.yml
  requirements.txt
Labels: CLA Signed

#2064 [TGA] Beam EOS score fix
  parlai/core/torch_generator_agent.py
Labels: CLA Signed

#2088 [Long] Update NLTK Version in Requirements
  requirements.txt
Labels: CLA Signed

#2074 [Utils] add offensive language classifier util
  parlai/agents/transformer_classifier/transformer_classifier.py
  parlai/mturk/tasks/image_chat/image_chat_collection/worlds.py
  parlai/mturk/tasks/personality_captions/personality_captions/worlds.py
  parlai/mturk/tasks/wizard_of_wikipedia/worlds.py
  parlai/scripts/detect_offensive_language.py
  parlai/tasks/dialogue_safety/agents.py
  parlai/utils/safety.py
  parlai/utils/testing.py
  tests/test_safety_modules.py
Labels: CLA Signed

#2077 Decrease runtime of quickstart test and move to nightly
  .circleci/config.yml
  tests/test_quickstart.sh
Labels: CLA Signed

#2093 Misc small fixes
  parlai/core/agents.py
  parlai/core/teachers.py
  parlai/scripts/convert_data_to_parlai_format.py
  parlai/tasks/fromfile/agents.py
Labels: CLA Signed

#2095 [WoW] Option for Prepending Knowledge in Generator Teacher
  parlai/tasks/wizard_of_wikipedia/agents.py
Labels: CLA Signed

#2099 Empty/None string bugs fixed for cornell_movie DoubleTeacher.
  parlai/tasks/cornell_movie/agents.py
Labels: CLA Signed

#2098 Move messenger/ to chat_service/
  README.md
  docs/source/tutorial_messenger.rst
  parlai/README.md
  parlai/chat_service/__init__.py
  parlai/chat_service/core/__init__.py
  parlai/chat_service/services/__init__.py
  parlai/chat_service/services/messenger/__init__.py
  parlai/chat_service/services/messenger/agents.py
  parlai/chat_service/services/messenger/message_sender.py
  parlai/chat_service/services/messenger/message_socket.py
  parlai/chat_service/services/messenger/messenger_manager.py
  parlai/chat_service/services/messenger/run.py
  parlai/chat_service/services/messenger/server/__init__.py
  parlai/chat_service/services/messenger/server/package.json
  parlai/chat_service/services/messenger/server/server.js
  parlai/chat_service/services/messenger/server_utils.py
  parlai/chat_service/services/messenger/shared_utils.py
  parlai/chat_service/services/messenger/world_runner.py
  parlai/chat_service/services/messenger/worlds.py
  parlai/chat_service/tasks/__init__.py
  parlai/chat_service/tasks/chatbot/__init__.py
  parlai/chat_service/tasks/chatbot/config.yml
  parlai/chat_service/tasks/chatbot/worlds.py
  parlai/chat_service/tasks/overworld_demo/__init__.py
  parlai/chat_service/tasks/overworld_demo/config.yml
  parlai/chat_service/tasks/overworld_demo/worlds.py
  parlai/chat_service/tasks/qa_data_collection/__init__.py
  parlai/chat_service/tasks/qa_data_collection/config.yml
  parlai/chat_service/tasks/qa_data_collection/worlds.py
Labels: CLA Signed, CS5152

#2109 Ignore .mypy_cache.
  .gitignore
Labels: CLA Signed

#2114 [TGA] Beam Blocking
  parlai/core/torch_generator_agent.py
  parlai/tasks/integration_tests/agents.py
  tests/test_transformers.py
Labels: CLA Signed

#2116 Report more BLEU and ROUGE metrics
  parlai/core/metrics.py
  tests/test_distributed.py
  tests/test_seq2seq.py
  tests/test_transformers.py
Labels: CLA Signed

#2119 Setup code coverage
  .circleci/config.yml
  .coveragerc
Labels: CLA Signed
