Repository facebookresearch/ParlAI, pull requests merged in 2019-09, with the labels that each got.

#1937 fix rouge setup errors
  parlai/core/metrics.py
Labels: CLA Signed

#1983 [WoW] Mturk evaluation task bug fix
  parlai/tasks/wizard_of_wikipedia/worlds.py
  projects/wizard_of_wikipedia/interactive_retrieval/interactive_retrieval.py
  projects/wizard_of_wikipedia/mturk_evaluation_task/worlds.py
Labels: CLA Signed

#1972 fixed bug for force_set of _set_text_vec with start/end tokens and mi…
  parlai/agents/bert_classifier/bert_classifier.py
  parlai/core/torch_classifier_agent.py
Labels: CLA Signed

#1947 fixing Talk The Walk MTurk task. …
  parlai/mturk/tasks/talkthewalk/html/Guide_index.html
  parlai/mturk/tasks/talkthewalk/html/Tourist_index.html
  parlai/mturk/tasks/talkthewalk/html/onboarding_index.html
  parlai/mturk/tasks/talkthewalk/worlds.py
Labels: CLA Signed

#1985 Dialogue safety: transformer classifier agent and teachers
  parlai/agents/transformer/modules.py
  parlai/agents/transformer_classifier/__init__.py
  parlai/agents/transformer_classifier/transformer_classifier.py
  parlai/core/torch_classifier_agent.py
  parlai/tasks/dialogue_safety/__init__.py
  parlai/tasks/dialogue_safety/agents.py
  parlai/tasks/dialogue_safety/base_agent.py
  parlai/tasks/dialogue_safety/build.py
  parlai/tasks/task_list.py
Labels: CLA Signed

#1992 Allow pickle when loading personas
  parlai/mturk/tasks/personachat/personachat_chat/worlds.py
Labels: CLA Signed

#1995 Add unzip to build_data and dnli dataset
  parlai/core/build_data.py
  parlai/tasks/dialogue_nli/__init__.py
  parlai/tasks/dialogue_nli/agents.py
  parlai/tasks/dialogue_nli/build.py
  parlai/tasks/task_list.py
Labels: CLA Signed, CS5152

#2002 [TTW] Fix TTW Download URL
  parlai/tasks/talkthewalk/build.py
Labels: CLA Signed

#1990 [Dialogue Safety] Pre-trained model release
  NEWS.md
  parlai/core/build_data.py
  parlai/zoo/dialogue_safety/__init__.py
  parlai/zoo/dialogue_safety/multi_turn.py
  parlai/zoo/dialogue_safety/single_turn.py
  parlai/zoo/model_list.py
  projects/dialogue_safety/README.md
Labels: CLA Signed

#2006 [Dialogue safety] add diagram to README
  projects/dialogue_safety/README.md
  projects/dialogue_safety/diagram.png
Labels: CLA Signed

#1996 Add CCPE dataset
  parlai/tasks/ccpe/__init__.py
  parlai/tasks/ccpe/agents.py
  parlai/tasks/ccpe/build.py
  parlai/tasks/task_list.py
Labels: CLA Signed, CS5152

#1993 [Poly-encoders] [GPU] Updates to Poly-encoder (and some Bi-encoder)
  parlai/agents/transformer/biencoder.py
  parlai/agents/transformer/modules.py
  parlai/agents/transformer/polyencoder.py
  parlai/agents/transformer/transformer.py
Labels: CLA Signed

#1997 Add Taskmaster-1 dataset
  parlai/tasks/task_list.py
  parlai/tasks/taskmaster/__init__.py
  parlai/tasks/taskmaster/agents.py
  parlai/tasks/taskmaster/build.py
  parlai/tasks/taskmaster/tm_utils.py
Labels: CLA Signed, CS5152, tasks

#2008 update vqa address
  parlai/tasks/vqa_v2/build.py
Labels: CLA Signed

#2009 Update Poly-encoder Builds/README
  parlai/zoo/pretrained_transformers/build.py
  projects/README.md
  projects/polyencoder/README.md
Labels: CLA Signed

#2016 Add reset button to interactive_web
  parlai/scripts/interactive_web.py
Labels: CLA Signed, CS5152

#1987 [TA] Report GPU memory usage.
  parlai/core/torch_agent.py
Labels: CLA Signed

#2017 [Bug-fix] Fix Self-Feeding fixed-cands issue
  projects/self_feeding/interactive.py
  projects/self_feeding/self_feeding_agent.py
Labels: CLA Signed

#2024 Update projects README: dialogue safety
  projects/README.md
Labels: CLA Signed

#2027 wiz doc update (small)
  projects/wizard_of_wikipedia/README.md
Labels: CLA Signed

#2025 [Empathetic Dialogues] Emotion Classification task
  parlai/tasks/empathetic_dialogues/agents.py
Labels: CLA Signed

#2003 Check for shared before dataparallel call
  parlai/agents/bert_ranker/bi_encoder_ranker.py
  parlai/agents/bert_ranker/cross_encoder_ranker.py
  parlai/agents/transformer/crossencoder.py
  parlai/agents/transformer/polyencoder.py
  parlai/core/torch_classifier_agent.py
Labels: CLA Signed

#2029 Fix sync issue when using pretrained embeddings.
  parlai/core/torch_agent.py
Labels: CLA Signed

#1944 Task feedback
  parlai/mturk/core/dev/mturk_manager.py
  parlai/mturk/core/mturk_manager.py
  parlai/mturk/core/react_server/dev/app.jsx
  parlai/mturk/core/react_server/dev/components/core_components.jsx
Labels: CLA Signed
