Repository facebookresearch/ParlAI, pull requests merged in 2019-12, with the labels that each got.

#2226 Delete the fairseq agent
  parlai/agents/README.md
  parlai/agents/fairseq/README.md
  parlai/agents/fairseq/__init__.py
  parlai/agents/fairseq/fairseq.py
  tests/test_fairseq.py
Labels: CLA Signed

#2234 self-chat logs: label->labels bug
  parlai/utils/world_logging.py
Labels: CLA Signed

#2230 UI Changes to interactive_web.py
  parlai/scripts/interactive_web.py
Labels: CLA Signed, CS5152

#2235 Add context blocking to TGA
  parlai/core/torch_generator_agent.py
  parlai/scripts/self_chat.py
  parlai/utils/testing.py
  tests/test_transformers.py
Labels: CLA Signed

#2237 Small modernizations to controllable dialogue mturk task.
  projects/controllable_dialogue/mturk/run.py
  projects/controllable_dialogue/mturk/worlds.py
Labels: CLA Signed

#2244 [TGA] Fix uncaught exception.
  parlai/core/torch_generator_agent.py
  tests/test_tga.py
Labels: CLA Signed

#2246 [WebSockets Service] Set debug based on the is_debug flag
  parlai/chat_service/services/websocket/websocket_manager.py
Labels: CLA Signed

#2247 [WebSockets Service] Cleanup WebSockets
  parlai/chat_service/services/websocket/agents.py
  parlai/chat_service/services/websocket/websocket_manager.py
Labels: CLA Signed

#2159 Implement local terminal chat service
  parlai/chat_service/services/terminal_chat/README.md
  parlai/chat_service/services/terminal_chat/__init__.py
  parlai/chat_service/services/terminal_chat/agents.py
  parlai/chat_service/services/terminal_chat/client.py
  parlai/chat_service/services/terminal_chat/run.py
  parlai/chat_service/services/terminal_chat/terminal_manager.py
Labels: CLA Signed

#2239 [BUG FIX] Fix eval model with `train:evalmode`
  parlai/core/teachers.py
  parlai/tasks/integration_tests/agents.py
  parlai/utils/testing.py
  tests/test_eval_model.py
Labels: CLA Signed

#2242 Add Amazon QA Dataset
  parlai/tasks/amazon_qa/__init__.py
  parlai/tasks/amazon_qa/agents.py
  parlai/tasks/amazon_qa/build.py
  parlai/tasks/task_list.py
Labels: CLA Signed

#2248 empathetic dialogues project link
  projects/README.md
Labels: CLA Signed

#2249 add message_partners to chat_service agents
  parlai/chat_service/core/agents.py
Labels: CLA Signed

#2252 Implements local browser chat service
  parlai/chat_service/services/browser_chat/README.md
  parlai/chat_service/services/browser_chat/__init__.py
  parlai/chat_service/services/browser_chat/agents.py
  parlai/chat_service/services/browser_chat/browser_manager.py
  parlai/chat_service/services/browser_chat/client.py
  parlai/chat_service/services/browser_chat/run.py
Labels: CLA Signed

#2257 [Utils] Display Processed Images in display_data
  parlai/utils/misc.py
Labels: CLA Signed

#2262 MTurk tests always run; OS X tests only run on master.
  .circleci/config.yml
  .circleci/triggers.py
Labels: CLA Signed

#2254 Alice Agent
  parlai/agents/alice/README.md
  parlai/agents/alice/__init__.py
  parlai/agents/alice/alice.py
  tests/nightly/cpu/test_alice.py
Labels: CLA Signed

#2251 Add OneCommon Dataset
  parlai/tasks/onecommon/README.md
  parlai/tasks/onecommon/__init__.py
  parlai/tasks/onecommon/agents.py
  parlai/tasks/onecommon/build.py
  parlai/tasks/task_list.py
Labels: CLA Signed

#2261 eval_model script saves log in json format
  parlai/scripts/eval_model.py
Labels: CLA Signed

#2043 self_observe
  parlai/core/torch_agent.py
  parlai/core/worlds.py
  parlai/scripts/build_pytorch_data.py
  projects/self_feeding/self_feeding_agent.py
  tests/test_torch_agent.py
Labels: CLA Signed

#2256 [TA] Fixed Torch Agent Dict Saving
  parlai/core/torch_agent.py
Labels: CLA Signed

#2216 Add type checking
  .circleci/config.yml
  mypy.ini
  parlai/agents/bert_ranker/bi_encoder_ranker.py
  parlai/agents/bert_ranker/helpers.py
  parlai/agents/legacy_agents/seq2seq/modules_v1.py
  parlai/agents/legacy_agents/seq2seq/seq2seq_v0.py
  parlai/agents/legacy_agents/seq2seq/utils_v0.py
  parlai/agents/memnn/modules.py
  parlai/agents/seq2seq/modules.py
  parlai/agents/starspace/starspace.py
  parlai/agents/transformer/modules.py
  parlai/agents/transformer/transformer.py
  parlai/chat_service/core/chat_service_manager.py
  parlai/chat_service/services/websocket/sockets.py
  parlai/core/teachers.py
  parlai/core/torch_agent.py
  parlai/core/torch_generator_agent.py
  parlai/core/torch_ranker_agent.py
  parlai/mturk/core/dev/socket_manager.py
  parlai/mturk/core/dev/test/test_full_system.py
  parlai/mturk/core/legacy_2018/test/test_full_system.py
  parlai/mturk/core/socket_manager.py
  parlai/mturk/core/test/test_full_system.py
  parlai/mturk/tasks/multi_agent_dialog/task_config.py
  parlai/mturk/tasks/qa_data_collection/task_config.py
  parlai/mturk/tasks/react_task_demo/react_custom_no_extra_deps/task_config.py
  parlai/mturk/tasks/react_task_demo/react_custom_with_deps/task_config.py
  parlai/mturk/webapp/server.py
  parlai/scripts/interactive_web.py
  parlai/tasks/coqa/build.py
  parlai/tasks/dailydialog/parse.py
  parlai/tasks/dstc7/build.py
  parlai/tasks/insuranceqa/build.py
  parlai/tasks/integration_tests/agents.py
  parlai/tasks/mutualfriends/build.py
  parlai/utils/misc.py
  parlai/utils/testing.py
  parlai/utils/thread.py
  parlai/utils/torch.py
  projects/controllable_dialogue/controllable_seq2seq/controllable_seq2seq.py
  projects/controllable_dialogue/controllable_seq2seq/modules.py
  projects/controllable_dialogue/mturk/model_configs.py
  projects/image_chat/interactive.py
  projects/personachat/kvmemnn/kvmemnn.py
  projects/personality_captions/interactive.py
  projects/self_feeding/self_feeding_agent.py
  projects/taskntalk/coopgame_agent.py
  projects/wizard_of_wikipedia/generator/agents.py
  projects/wizard_of_wikipedia/generator/modules.py
  tests/suites.py
  tests/test_utils.py
Labels: CLA Signed

#2126 Prevent -dt train in eval_model without evalmode.
  parlai/scripts/eval_model.py
  tests/test_eval_model.py
Labels: CLA Signed

#2265 Make shebang failure fatal.
  parlai/agents/alice/__init__.py
  tests/check_copyright.py
Labels: CLA Signed

#2264 Fix MovieDialog.
  parlai/tasks/moviedialog/build.py
Labels: CLA Signed

#2266 Move opt; annotate some parameters with Opt
  parlai/core/agents.py
  parlai/core/dict.py
  parlai/core/gpt2_helper.py
  parlai/core/logs.py
  parlai/core/opt.py
  parlai/core/params.py
  parlai/core/torch_agent.py
  parlai/core/torch_classifier_agent.py
  parlai/core/torch_generator_agent.py
  parlai/core/torch_ranker_agent.py
  parlai/core/worlds.py
  parlai/tasks/integration_tests/agents.py
  parlai/utils/misc.py
  tests/test_dict.py
  tests/test_utils.py
Labels: CLA Signed

#2275 Black linting
  parlai/agents/bert_ranker/helpers.py
  parlai/core/torch_agent.py
  parlai/mturk/core/mturk_data_handler.py
  parlai/mturk/core/mturk_manager.py
  tests/test_transformers.py
  tests/test_utils.py
Labels: CLA Signed

#2276 [MTurk] No qualifications in sandbox mode
  parlai/mturk/core/mturk_manager.py
Labels: CLA Signed

#2271 [light] Small light interactive bugs
  parlai/tasks/light_dialog/worlds.py
Labels: CLA Signed

#2280 Fix one syntax error. Reword 'Task: " to " models".
  docs/source/generate_zoo_list.py
  parlai/core/build_data.py
Labels: CLA Signed, docs

#2285 update the README
  README.md
  docs/source/_static/img/parlai_examples.png
Labels: CLA Signed

#2283 Add support for markdown in docs.
  .circleci/config.yml
  docs/source/conf.py
  docs/source/index.rst
  requirements.txt
Labels: CLA Signed

#2274 Update maintainers.
  README.md
Labels: CLA Signed

#2288 [DocDay] Chat Service README
  parlai/chat_service/README.md
Labels: CLA Signed

#2149 Refactors messenger to use base classes
  parlai/chat_service/core/chat_service_manager.py
  parlai/chat_service/core/manager_utils.py
  parlai/chat_service/services/messenger/agents.py
  parlai/chat_service/services/messenger/message_socket.py
  parlai/chat_service/services/messenger/messenger_manager.py
  parlai/chat_service/services/messenger/world_runner.py
Labels: CLA Signed

#2286 [DocDay] Agent README Updates
  docs/Makefile
  docs/source/agents_list.rst
  docs/source/generate_agent_list.py
  docs/source/index.rst
  parlai/agents/legacy_agents/README.md
  parlai/agents/seq2seq/README.md
  parlai/agents/test_agents/README.md
  parlai/agents/tfidf_retriever/README.md
  parlai/agents/transformer/README.md
  parlai/agents/transformer/classifier.py
  parlai/agents/transformer/transformer.py
  parlai/agents/transformer_classifier/transformer_classifier.py
  parlai/utils/safety.py
  parlai/zoo/model_list.py
  projects/dialogue_safety/README.md
Labels: CLA Signed

#2289 Interactive + Self-chat + Pretty display docs
  docs/source/tutorial_basic.rst
  docs/source/tutorial_tipsntricks.rst
  projects/wizard_of_wikipedia/chat_example1.jsonl
  projects/wizard_of_wikipedia/chat_example2.jsonl
Labels: CLA Signed

#2287 Core README
  parlai/core/README.md
  parlai/core/torch_agent.py
Labels: CLA Signed

#2281 small fix for message class convai2/interactive.py
  projects/convai2/interactive.py
Labels: CLA Signed

#2157 Small changes to eval_wordstat.
  parlai/scripts/eval_wordstat.py
Labels: CLA Signed

#2296 Small update to docstring.
  parlai/scripts/train_model.py
Labels: CLA Signed

#2279 [Eval model] Save model replies
  parlai/scripts/eval_model.py
  parlai/utils/world_logging.py
Labels: CLA Signed

#1969 Continued battle with test_distributed
  parlai/core/build_data.py
  parlai/core/torch_generator_agent.py
  parlai/scripts/multiprocessing_train.py
  parlai/utils/distributed.py
  tests/test_distributed.py
Labels: CLA Signed, codequality

#2295 [Docs] Remove Reference Agents Section
  docs/source/example_seq2seq.rst
  docs/source/index.rst
  docs/source/repeat_label.rst
  docs/source/unigram_agent.rst
Labels: CLA Signed

#2268 [DoDeca] IGC Task
  parlai/core/teachers.py
  parlai/tasks/igc/__init__.py
  parlai/tasks/igc/agents.py
  parlai/tasks/task_list.py
  parlai/utils/typing.py
  tests/tasks/test_igc.py
Labels: CLA Signed

#2294 [Chat Services] update docs
  docs/source/index.rst
  docs/source/tutorial_basic.rst
  docs/source/tutorial_chat_service.md
  docs/source/tutorial_messenger.rst
Labels: CLA Signed

#2301 Remove broken line I missed from Eric's review
  docs/source/index.rst
Labels: CLA Signed

#2303 Update EmpatheticDialogues teachers
  parlai/tasks/empathetic_dialogues/README.md
  parlai/tasks/empathetic_dialogues/agents.py
  parlai/tasks/empathetic_dialogues/build.py
  parlai/tasks/task_list.py
  tests/tasks/test_empathetic_dialogues.py
Labels: CLA Signed

#2307 Transformer incremental decoding
  parlai/agents/transformer/modules.py
  projects/wizard_of_wikipedia/generator/modules.py
Labels: CLA Signed
