Repository facebookresearch/ParlAI, pull requests merged in 2019-08, with the labels that each got.

#1888 [Bug Fix]Fix Metrics type issue in convai2 circleci test
  parlai/core/metrics.py
Labels: CLA Signed

#1855 [MTurk] Better HIT management on shutdown
  parlai/mturk/core/dev/mturk_manager.py
Labels: CLA Signed, MTurk

#1893 only print number of threads initialized, not init per thread
  parlai/core/worlds.py
Labels: CLA Signed

#1892 [MTurk] Testing for the dev branch
  parlai/mturk/core/dev/agents.py
  parlai/mturk/core/dev/mturk_manager.py
  parlai/mturk/core/dev/socket_manager.py
  parlai/mturk/core/dev/test/test_db_interactions.py
  parlai/mturk/core/dev/test/test_full_system.py
  parlai/mturk/core/dev/test/test_mturk_agent.py
  parlai/mturk/core/dev/test/test_mturk_manager.py
  parlai/mturk/core/dev/test/test_socket_manager.py
  parlai/mturk/core/dev/test/test_worker_manager.py
Labels: CLA Signed

#1826 Message object
  parlai/agents/bert_ranker/bi_encoder_ranker.py
  parlai/agents/bert_ranker/cross_encoder_ranker.py
  parlai/agents/language_model/language_model.py
  parlai/agents/memnn/memnn.py
  parlai/agents/transformer/biencoder.py
  parlai/agents/transformer/crossencoder.py
  parlai/agents/transformer/polyencoder.py
  parlai/core/message.py
  parlai/core/teachers.py
  parlai/core/torch_agent.py
  parlai/core/utils.py
  parlai/core/worlds.py
  parlai/scripts/build_candidates.py
  parlai/scripts/build_pytorch_data.py
  parlai/scripts/verify_data.py
  projects/controllable_dialogue/controllable_seq2seq/controllable_seq2seq.py
  projects/image_chat/transresnet_multimodal/modules.py
  projects/image_chat/transresnet_multimodal/transresnet_multimodal.py
  projects/self_feeding/README.md
  projects/self_feeding/self_feeding_agent.py
  projects/wizard_of_wikipedia/interactive_retrieval/interactive_retrieval.py
  projects/wizard_of_wikipedia/wizard_transformer_ranker/wizard_transformer_ranker.py
  tests/nightly/gpu/test_transresnet_multimodal.py
  tests/test_messages.py
  tests/test_torch_agent.py
  tests/test_utils.py
Labels: CLA Signed

#1894 fixed bug in fixed candidate ranking and add speedup option for ranking eval
  parlai/core/torch_ranker_agent.py
Labels: CLA Signed

#1897 Output git commit during parse_args.
  parlai/core/params.py
Labels: CLA Signed

#1901 [TorchRankerAgent]get batch size by batch.image in case bact.text_vec is None
  parlai/core/torch_ranker_agent.py
Labels: CLA Signed

#1902 Fix try/catch in `print_git_commit`
  parlai/core/params.py
Labels: CLA Signed

#1895 print how long evals take during training
  parlai/scripts/train_model.py
Labels: CLA Signed, enhancement

#1898 fix dataloader sharing
  parlai/core/teachers.py
Labels: CLA Signed, bug

#1903 Fix broken flag in docs
  parlai/zoo/pretrained_transformers/README.md
Labels: CLA Signed

#1905 Update masking for Torch 1.2
  parlai/agents/seq2seq/modules.py
Labels: CLA Signed

#1904 make codec dir
  parlai/core/dict.py
Labels: CLA Signed

#1910 pytorch 1.2 compatibility
  projects/controllable_dialogue/controllable_seq2seq/controllable_seq2seq.py
  projects/controllable_dialogue/controllable_seq2seq/modules.py
  projects/wizard_of_wikipedia/generator/agents.py
Labels: CLA Signed

#1837 Fix resume-from-checkpoint bugs.
  parlai/agents/test_agents/__init__.py
  parlai/agents/test_agents/dummy_torch_agent.py
  parlai/core/torch_agent.py
  tests/test_torch_agent.py
Labels: CLA Signed

#1908 Space tokenization.
  parlai/core/dict.py
  tests/test_dict.py
Labels: CLA Signed

#1913 Fail loudly when running TorchAgent in mturk if interactive mode is False
  parlai/agents/test_agents/dummy_torch_agent.py
  parlai/core/params.py
  parlai/core/torch_agent.py
  parlai/core/torch_generator_agent.py
  parlai/core/torch_ranker_agent.py
  tests/test_torch_agent.py
Labels: CLA Signed

#1919 Pytorch version tests.
  .circleci/config.yml
  README.md
Labels: CLA Signed

#1923 Support both shorthands in display_data/model.py
  parlai/scripts/display_data.py
  parlai/scripts/display_model.py
Labels: CLA Signed

#1916 [TRA] Train predictions fix
  parlai/core/torch_ranker_agent.py
Labels: CLA Signed

#1915 Quiet the rouge warning.
  parlai/core/metrics.py
Labels: CLA Signed

#1926 ConvAI2 Bi-Encoder
  parlai/zoo/model_list.py
Labels: CLA Signed

#1924 [LIGHT] No affordance ablation
  parlai/scripts/verify_data.py
  parlai/tasks/light_dialog/agents.py
  parlai/tasks/light_dialog/build.py
  parlai/tasks/light_dialog/builder.py
Labels: CLA Signed

#1930 Black some things that have slipped through.
  parlai/tasks/image_chat/agents.py
  parlai/zoo/model_list.py
Labels: CLA Signed

#1889 WoW end2end interactive.
  projects/wizard_of_wikipedia/README.md
  projects/wizard_of_wikipedia/generator/agents.py
  projects/wizard_of_wikipedia/interactive_end2end/__init__.py
  projects/wizard_of_wikipedia/interactive_end2end/interactive_end2end.py
Labels: CLA Signed

#1935 Ensure programatic arg parsing behaves the same as using actual CLI.
  parlai/core/params.py
Labels: CLA Signed

#1939 LocalHuman: add Messages
  parlai/agents/local_human/local_human.py
Labels: CLA Signed

#1943 Poly-encoder project doc
  projects/README.md
  projects/polyencoder/README.md
Labels: CLA Signed

#1932 Messages fixes for teachers.py
  parlai/core/teachers.py
Labels: CLA Signed

#1942 [TransformerRanker] Allow passing context segments into MemNet forward
  parlai/agents/transformer/modules.py
Labels: CLA Signed

#1925 [TGA] refactor beam search
  parlai/core/torch_generator_agent.py
  tests/test_seq2seq.py
  tests/test_tga.py
  tests/test_transformers.py
Labels: CLA Signed

#1945 [TRA] vocab candidates bug fix
  parlai/agents/transformer/polyencoder.py
  parlai/core/torch_ranker_agent.py
Labels: CLA Signed

#1948 [ConvAI2 Interactive World] bug fix for Message
  parlai/tasks/convai2/worlds.py
Labels: CLA Signed

#1951 [Safety] add a README
  projects/dialogue_safety/README.md
Labels: CLA Signed

#1941 Minor cleanups
  parlai/agents/bert_ranker/helpers.py
  parlai/core/agents.py
  parlai/core/worlds.py
Labels: CLA Signed

#1906 AbstractImageTeacher and download_multiprocess
  parlai/core/build_data.py
  parlai/core/image_featurizers.py
  parlai/core/teachers.py
  parlai/scripts/build_dict.py
  requirements.txt
  tests/test_build_data.py
Labels: CLA Signed

#1978 Print capacity
  parlai/core/torch_ranker_agent.py
Labels: CLA Signed
