Repository facebookresearch/ParlAI, pull requests merged in 2019-04, with the labels that each got.

#1597 [MTurk] Slightly improved checking around socket edge cases
  parlai/mturk/core/socket_manager.py
Labels: CLA Signed

#1588 Fixing argument name mismatch for MemNN
  parlai/agents/memnn/modules.py
Labels: CLA Signed

#1595 Skip empty text_vec examples in seq2seq.
  parlai/agents/seq2seq/seq2seq.py
  parlai/tasks/integration_tests/agents.py
  tests/test_seq2seq.py
  tests/test_transformers.py
Labels: CLA Signed

#1562 Forceful saving of dictionaries
  parlai/agents/fairseq/fairseq.py
  parlai/agents/seq2seq/seq2seq.py
  parlai/core/torch_agent.py
Labels: CLA Signed

#1599 clean form field after sending
  parlai/mturk/core/react_server/dev/components/core_components.jsx
Labels: CLA Signed

#1600 Fix Dict Saving
  parlai/core/dict.py
Labels: CLA Signed

#1602 [MTurk] Re-enabling socket tests on circle
  parlai/mturk/core/test/test_full_system.py
  parlai/mturk/core/test/test_mturk_manager.py
  parlai/mturk/core/test/test_socket_manager.py
  requirements.txt
Labels: CLA Signed

#1605 Fix nightly CPU tests
  .circleci/config.yml
  parlai/core/testing_utils.py
  tests/nightly/cpu/test_pytorch_data_teacher_integration.py
  tests/test_seq2seq.py
Labels: CLA Signed

#1598 Update FastText URLs.
  parlai/core/torch_agent.py
  parlai/zoo/fasttext_cc_vectors/build.py
  parlai/zoo/fasttext_vectors/build.py
Labels: CLA Signed

#1606 Support --validation-max-exs for final evaluation.
  parlai/scripts/train_model.py
  parlai/tasks/convai2/agents.py
  tests/nightly/gpu/test_bert.py
  tests/test_eval_model.py
  tests/test_train_model.py
Labels: CLA Signed

#1601 [circleci] Conditional tests
  .circleci/config.yml
  .circleci/triggers.py
  CONTRIBUTING.md
  parlai/core/testing_utils.py
  parlai/core/utils.py
  setup.py
  tests/datatests/test_new_tasks.py
  tests/suites.py
Labels: CLA Signed

#1607 CircleCI badges
  README.md
  website/generate.py
Labels: CLA Signed

#1608 Give example of overriding defaults in TorchAgent.
  parlai/core/torch_agent.py
Labels: CLA Signed

#1609 [circleci] Build website step (&& squash with master.)
  .circleci/config.yml
  README.md
  docs/source/generate_zoo_list.py
  website/generate.py
Labels: CLA Signed

#1611 [circleci] fix git freeze.
  .circleci/config.yml
Labels: CLA Signed

#1612 Revert the git squash idea of #1609.
  .circleci/config.yml
Labels: CLA Signed

#1610 [MTurk] Adding more support for 1 person static tasks.
  parlai/mturk/core/mturk_manager.py
  parlai/mturk/core/mturk_utils.py
  parlai/mturk/core/react_server/dev/app.jsx
  parlai/mturk/core/react_server/dev/components/core_components.jsx
  parlai/mturk/core/react_server/dev/components/mturk_submit_form.jsx
  parlai/mturk/core/react_server/dev/components/socket_handler.jsx
  parlai/mturk/core/react_server/server/server.js
  parlai/mturk/core/react_server/server/static/index.html
  parlai/mturk/core/socket_manager.py
  parlai/mturk/core/worlds.py
Labels: CLA Signed

#1613 Missing dict file
  parlai/core/agents.py
Labels: CLA Signed

#1614 Delete simple class in tensorboardX.
  parlai/core/logs.py
Labels: CLA Signed

#1621 [TRA] load candidates to CPU
  parlai/core/torch_ranker_agent.py
Labels: CLA Signed

#1617 Adjust indenting block
  parlai/core/teachers.py
Labels: CLA Signed

#1618 Reformat docstrings.
  parlai/core/agents.py
  parlai/core/build_data.py
  parlai/core/dict.py
  parlai/core/distributed_utils.py
  parlai/core/image_featurizers.py
  parlai/core/metrics.py
  parlai/core/params.py
  parlai/core/teachers.py
  parlai/core/thread_utils.py
  parlai/core/torch_agent.py
  parlai/core/torch_classifier_agent.py
  parlai/core/torch_generator_agent.py
  parlai/core/torch_ranker_agent.py
  parlai/core/utils.py
  parlai/core/worlds.py
Labels: CLA Signed

#1623 [Wizard of Wikipedia] Interactive retrieval and MTurk evaluation
  parlai/mturk/tasks/wizard_of_wikipedia/README.md
  parlai/zoo/wizard_of_wikipedia/full_dialogue_retrieval_model.py
  projects/wizard_of_wikipedia/README.md
  projects/wizard_of_wikipedia/interactive_retrieval/interactive_retrieval.py
  projects/wizard_of_wikipedia/mturk_evaluation_task/README.md
  projects/wizard_of_wikipedia/mturk_evaluation_task/__init__.py
  projects/wizard_of_wikipedia/mturk_evaluation_task/html/PERSON_1_index.html
  projects/wizard_of_wikipedia/mturk_evaluation_task/html/PERSON_2_index.html
  projects/wizard_of_wikipedia/mturk_evaluation_task/html/onboarding_index.html
  projects/wizard_of_wikipedia/mturk_evaluation_task/run.py
  projects/wizard_of_wikipedia/mturk_evaluation_task/task_config.py
  projects/wizard_of_wikipedia/mturk_evaluation_task/worlds.py
  projects/wizard_of_wikipedia/scripts/interactive_retrieval_model.py
Labels: CLA Signed

#1625 [WoW] retrieval opt fix
  projects/wizard_of_wikipedia/scripts/eval_retrieval_model.py
Labels: CLA Signed

#1628 Attempt to mark this test as flaky.
  parlai/mturk/core/test/test_full_system.py
Labels: CLA Signed

#1630 [MTurk] Removing old package lock
  parlai/mturk/core/react_server/package-lock.json
Labels: CLA Signed, MTurk

#1632 Use a more sensible maxlen than 1.
  parlai/core/torch_generator_agent.py
Labels: CLA Signed

#1633 [MTurk] Updating sequelize
  parlai/mturk/core/dev/react_server/server/package.json
  parlai/mturk/core/dev/server_legacy/package.json
  parlai/mturk/core/legacy_2018/react_server/server/package.json
  parlai/mturk/core/legacy_2018/server_legacy/package.json
  parlai/mturk/core/react_server/server/package.json
  parlai/mturk/core/server_legacy/package.json
Labels: CLA Signed, MTurk

#1634 [MTurk] Moving scripts directory
  parlai/mturk/README.md
  parlai/mturk/core/README.md
  parlai/mturk/core/legacy_2018/scripts/__init__.py
  parlai/mturk/core/legacy_2018/scripts/auto_complete_hit.py
  parlai/mturk/core/legacy_2018/scripts/bonus_workers.py
  parlai/mturk/core/legacy_2018/scripts/delete_hits.py
  parlai/mturk/core/scripts/auto_complete_hit.py
  parlai/mturk/core/scripts/bonus_workers.py
  parlai/mturk/core/scripts/delete_hits.py
  parlai/mturk/scripts/__init__.py
  parlai/mturk/scripts/auto_complete_hit.py
  parlai/mturk/scripts/bonus_workers.py
  parlai/mturk/scripts/delete_hits.py
Labels: CLA Signed

#1637 [MTurk] Moving run_data
  parlai/mturk/.gitignore
  parlai/mturk/README.md
  parlai/mturk/core/README.md
  parlai/mturk/core/dev/.gitignore
  parlai/mturk/core/dev/README.md
  parlai/mturk/core/dev/mturk_data_handler.py
  parlai/mturk/core/legacy_2018/.gitignore
  parlai/mturk/core/legacy_2018/README.md
  parlai/mturk/core/legacy_2018/mturk_data_handler.py
  parlai/mturk/core/mturk_data_handler.py
Labels: CLA Signed, MTurk

#1616 Convai2 Tests
  parlai/core/testing_utils.py
  projects/convai2/baselines/kvmemnn/eval_f1.py
  projects/convai2/baselines/kvmemnn/eval_hits.py
  projects/convai2/baselines/language_model/eval_f1.py
  projects/convai2/baselines/seq2seq/eval_f1.py
  projects/convai2/baselines/seq2seq/eval_hits.py
  projects/convai2/eval_f1.py
  projects/convai2/eval_hits.py
  tests/nightly/gpu/test_bert.py
  tests/nightly/gpu/test_convai2.py
Labels: CLA Signed

#1636 [MTurk] Fixing onboarding test possibly
  parlai/mturk/core/dev/test/test_full_system.py
  parlai/mturk/core/legacy_2018/test/test_full_system.py
  parlai/mturk/core/test/test_full_system.py
Labels: CLA Signed, MTurk

#1640 [BERT Classifier] cache pre-trained files
  parlai/agents/bert_classifier/bert_classifier.py
Labels: CLA Signed

#1642 [MTurk] Using a tmp dir for scratch work.
  parlai/core/params.py
  parlai/mturk/core/dev/mturk_data_handler.py
  parlai/mturk/core/dev/mturk_manager.py
  parlai/mturk/core/dev/mturk_utils.py
  parlai/mturk/core/dev/server_utils.py
  parlai/mturk/core/dev/shared_utils.py
  parlai/mturk/core/legacy_2018/mturk_data_handler.py
  parlai/mturk/core/legacy_2018/mturk_manager.py
  parlai/mturk/core/legacy_2018/mturk_utils.py
  parlai/mturk/core/legacy_2018/server_utils.py
  parlai/mturk/core/legacy_2018/shared_utils.py
  parlai/mturk/core/mturk_manager.py
  parlai/mturk/core/mturk_utils.py
  parlai/mturk/core/server_utils.py
  parlai/mturk/core/shared_utils.py
Labels: CLA Signed

#1643 BPE TorchAgent save bugs
  parlai/core/dict.py
Labels: CLA Signed

#1644 [MTurk] Static done button shows up on bottom of left pane when done
  parlai/mturk/core/dev/react_server/dev/components/core_components.jsx
  parlai/mturk/core/legacy_2018/react_server/dev/components/core_components.jsx
  parlai/mturk/core/react_server/dev/components/core_components.jsx
Labels: MTurk

#1641 [MemNN] Time feature bug fix
  parlai/agents/memnn/memnn.py
  parlai/agents/memnn/modules.py
Labels: CLA Signed

#1572 Transformer GELU activations and XLM/Bert architectures.
  parlai/agents/transformer/modules.py
  parlai/agents/transformer/transformer.py
  tests/test_transformers.py
Labels: CLA Signed

#1650 Pull out the dictionary construction
  parlai/agents/memnn/memnn.py
  parlai/core/torch_agent.py
Labels: CLA Signed

#1662 Issues templates
  .github/ISSUE_TEMPLATE/agent-bug.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/mturk-bug.md
  .github/ISSUE_TEMPLATE/other.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: CLA Signed

#1661 New DailyDialog Teacher to exclude __SILENCE__ tokens
  parlai/tasks/dailydialog/agents.py
Labels: CLA Signed

#1664 [MTurk] Treat abandons as a special case of returns
  parlai/mturk/core/dev/mturk_manager.py
  parlai/mturk/core/legacy_2018/mturk_manager.py
  parlai/mturk/core/mturk_manager.py
Labels: CLA Signed

#1667 Try moving the PR template.
  .github/pull_request_template.md
Labels: CLA Signed

#1668 Fix setting of PARLAI_DATAPATH and PARLAI_DOWNPATH env variables
  parlai/core/params.py
Labels: CLA Signed

#1669 No need for yaml titles in PR template.
  .github/pull_request_template.md
Labels: CLA Signed

#1666 Don't copy datapath from disk opt files.
  parlai/core/agents.py
Labels: CLA Signed

#1671 Update train_end2end.py
  projects/wizard_of_wikipedia/generator/train_end2end.py
Labels: CLA Signed

#1673 Fix download issues with new datapath logic.
  parlai/core/params.py
Labels: CLA Signed

#1676 Another test typo.
  tests/test_transformers.py
Labels: CLA Signed

#1677 [MTurk] removing legacy from dev code
  parlai/mturk/core/dev/README.md
  parlai/mturk/core/dev/agents.py
  parlai/mturk/core/dev/mturk_data_handler.py
  parlai/mturk/core/dev/mturk_manager.py
  parlai/mturk/core/dev/server_legacy/__init__.py
  parlai/mturk/core/dev/server_legacy/html/core.html
  parlai/mturk/core/dev/server_legacy/html/cover_page.html
  parlai/mturk/core/dev/server_legacy/html/mturk_index.html
  parlai/mturk/core/dev/server_legacy/package.json
  parlai/mturk/core/dev/server_legacy/server.js
  parlai/mturk/core/dev/server_utils.py
  parlai/mturk/core/dev/socket_manager.py
  parlai/mturk/core/dev/worker_manager.py
Labels: CLA Signed

#1679 [WoW] fix for M-Turk evaluation task
  projects/wizard_of_wikipedia/mturk_evaluation_task/worlds.py
Labels: CLA Signed

#1683 Adding survey to MTurkManager Shutdown
  parlai/mturk/core/mturk_manager.py
Labels: CLA Signed

#1682 Survey link for train_model and eval_model
  parlai/scripts/eval_model.py
  parlai/scripts/train_model.py
Labels: CLA Signed
