Repository facebookresearch/ParlAI, pull requests merged in 2020-09, with the labels that each got.

#2916 Aligning header elements to the center
  README.md
Labels: CLA Signed, stale

#3027 Adding option to load pretrained model from directory for gpt2
  parlai/agents/hugging_face/dict.py
  parlai/agents/hugging_face/gpt2.py
Labels: CLA Signed

#3031 Fix <hr/> in readme
  README.md
Labels: CLA Signed

#3035 Store website artifacts.
  .circleci/config.yml
Labels: CLA Signed

#3038 Old dict file fix
  parlai/core/agents.py
Labels: CLA Signed

#3041 [DOC DAY] Updating installation instructions
  README.md
  requirements.txt
Labels: CLA Signed

#3042 [DOC DAY] Update docs generation instructions
  docs/README.md
Labels: CLA Signed

#3047 [Doc Day] Contribution Guide
  docs/source/cli_advanced.md
  docs/source/tutorial_tipsntricks.md
Labels: CLA Signed

#3044 [Doc Day] Writing Tests in ParlAI, a tutorial
  docs/source/index.md
  docs/source/tutorial_tests.md
Labels: CLA Signed

#3050 [Chat Services] Browser Chat Bug Fix
  parlai/chat_service/services/browser_chat/client.py
  parlai/chat_service/tasks/chatbot/worlds.py
Labels: CLA Signed

#3046 [DOC DAY] ParlaiScript tutorial
  docs/source/cli_custom.md
  docs/source/index.md
Labels: CLA Signed

#3048 [DOC DAY] Chat Services
  docs/source/chat_service.md
  docs/source/index.md
  docs/source/tutorial_chat_service.md
  parlai/chat_service/README.md
  parlai/chat_service/services/websocket/websocket_manager.py
  requirements.txt
Labels: CLA Signed

#3054 Conversations format JsonFile fixes
  parlai/core/teachers.py
  parlai/tasks/jsonfile/README.md
  parlai/tasks/jsonfile/agents.py
  parlai/tasks/jsonfile/example_data.json
  parlai/utils/conversations.py
  tests/test_teachers.py
Labels: CLA Signed

#3034 Fixes to Reward Unlikelihood agent
  projects/dialogue_unlikelihood/agents.py
Labels: CLA Signed

#3052 Test and details in convo render
  parlai/scripts/convo_render.py
  tests/test_convo_render.py
Labels: CLA Signed

#3036 Reorganize high level slightly.
  docs/source/faq.md
  docs/source/index.md
Labels: CLA Signed

#3025 LR Scheduler fixes
  parlai/agents/test_agents/unigram.py
  parlai/core/torch_agent.py
  parlai/nn/lr_scheduler.py
  parlai/scripts/train_model.py
  tests/test_lr_schedulers.py
  tests/test_transformers.py
  tests/test_unigram.py
Labels: CLA Signed

#3026 Improve coverage of some base agents
  .coveragerc
  parlai/agents/ir_baseline/ir_baseline.py
  parlai/agents/starspace/starspace.py
  parlai/agents/tfidf_retriever/build_db.py
  parlai/agents/tfidf_retriever/build_tfidf.py
  parlai/agents/tfidf_retriever/doc_db.py
  parlai/agents/tfidf_retriever/tfidf_doc_ranker.py
  parlai/agents/tfidf_retriever/tfidf_retriever.py
  parlai/agents/tfidf_retriever/tokenizers/__init__.py
  parlai/agents/tfidf_retriever/tokenizers/corenlp_tokenizer.py
  parlai/agents/tfidf_retriever/tokenizers/tokenizer.py
  parlai/agents/tfidf_retriever/utils.py
  parlai/scripts/convert_data_to_fasttext_format.py
  parlai/scripts/detect_offensive_language.py
  parlai/scripts/party.py
  parlai/scripts/verify_data.py
  parlai/utils/bpe.py
  tests/test_interactive.py
  tests/test_ir_baseline.py
  tests/test_other_scripts.py
  tests/test_starspace.py
  tests/test_tfidf_retriever.py
Labels: CLA Signed

#2954 Cache data directory for tests
  .circleci/config.yml
  conftest.py
  tests/test_quickstart.sh
Labels: CLA Signed

#3057 Fix typo
  docs/source/tutorial_basic.md
Labels: CLA Signed

#3043 [DOC DAY] Self chat feature branch
  docs/source/tutorial_tipsntricks.md
Labels: CLA Signed

#3045 [DOC DAY] Update task tutorial
  docs/source/tutorial_task.md
  parlai/core/teachers.py
  parlai/tasks/babi/agents.py
  parlai/tasks/booktest/agents.py
  parlai/tasks/cbt/agents.py
  parlai/tasks/convai2/agents.py
  parlai/tasks/cornell_movie/agents.py
  parlai/tasks/dbll_babi/agents.py
  parlai/tasks/dbll_movie/agents.py
  parlai/tasks/dialog_babi/agents.py
  parlai/tasks/dialog_babi_plus/agents.py
  parlai/tasks/fromfile/agents.py
  parlai/tasks/funpedia/agents.py
  parlai/tasks/insuranceqa/agents.py
  parlai/tasks/mctest/agents.py
  parlai/tasks/moviedialog/agents.py
  parlai/tasks/ms_marco/agents.py
  parlai/tasks/mturkwikimovies/agents.py
  parlai/tasks/opensubtitles/agents.py
  parlai/tasks/personachat/agents.py
  parlai/tasks/personalized_dialog/agents.py
  parlai/tasks/qacnn/agents.py
  parlai/tasks/qadailymail/agents.py
  parlai/tasks/scan/agents.py
  parlai/tasks/simplequestions/agents.py
  parlai/tasks/webquestions/agents.py
  parlai/tasks/wikimovies/agents.py
  parlai/tasks/wikiqa/agents.py
  parlai/tasks/wmt/agents.py
  projects/self_feeding/utils.py
  tests/test_import.py
Labels: CLA Signed

#3056 Version 0.9.1.
  parlai/__init__.py
  setup.py
Labels: CLA Signed

#3060 [BART] Don't override init if it exists
  parlai/agents/bart/bart.py
Labels: CLA Signed

#3065 [BART] allow overriding BART args
  parlai/agents/bart/bart.py
Labels: CLA Signed

#3063 fromfile warning for using valid/test
  parlai/tasks/fromfile/agents.py
Labels: CLA Signed

#3068 Fix masked_fill no-op
  parlai/agents/transformer/modules.py
Labels: CLA Signed

#3067 Fix typo in tensorboard.
  parlai/__init__.py
  parlai/core/logs.py
  setup.py
Labels: CLA Signed

#3061 jsonfile doc
  docs/source/tutorial_task.md
  parlai/tasks/jsonfile/README.md
Labels: CLA Signed

#3072 Add multiwoz v2.0
  parlai/tasks/multiwoz_v20/__init__.py
  parlai/tasks/multiwoz_v20/agents.py
  parlai/tasks/multiwoz_v20/build.py
  parlai/tasks/multiwoz_v21/__init__.py
  parlai/tasks/multiwoz_v21/agents.py
  parlai/tasks/multiwoz_v21/build.py
  parlai/tasks/task_list.py
Labels: CLA Signed

#3073 Two inaugural FAQ questions
  docs/source/faq.md
Labels: CLA Signed

#3079 Always download data on interactive wizard.
  parlai/tasks/wizard_of_wikipedia/worlds.py
Labels: CLA Signed

#3077 Disable zipfile serialization option of torch.save
  parlai/utils/torch.py
Labels: CLA Signed

#3081 Self-chat batch size assertion error
  parlai/scripts/self_chat.py
Labels: CLA Signed

#3069 Change drqa default tokenizer.
  parlai/agents/drqa/drqa.py
Labels: CLA Signed

#3055 [tests] Switch to OverfitTeacher for some model tests.
  .circleci/config.yml
  parlai/core/opt.py
  parlai/core/worlds.py
  parlai/scripts/train_model.py
  parlai/tasks/integration_tests/agents.py
  tests/nightly/gpu/test_dialogpt.py
  tests/nightly/gpu/test_drqa.py
  tests/test_distributed.py
  tests/test_dynamicbatching.py
  tests/test_hred.py
  tests/test_memnn.py
  tests/test_other_scripts.py
  tests/test_seq2seq.py
  tests/test_tra.py
  tests/test_transformers.py
Labels: CLA Signed

#2678 TaskMaster-2
  parlai/tasks/task_list.py
  parlai/tasks/taskmaster2/README.md
  parlai/tasks/taskmaster2/__init__.py
  parlai/tasks/taskmaster2/agents.py
  parlai/tasks/taskmaster2/build.py
Labels: CLA Signed, never-stale

#3086 [TCA] Add number of parameters print statement
  parlai/core/torch_classifier_agent.py
Labels: CLA Signed

#3049 [Doc Day] Totally rewrite Worlds docs.
  docs/source/_static/img/world_batchboth.png
  docs/source/_static/img/world_hogwild.png
  docs/source/tutorial_basic.md
  docs/source/tutorial_worlds.md
Labels: CLA Signed

#3006 Adding features into the human+model turn annotation task
  docs/source/tutorial_mturk.md
  parlai/crowdsourcing/utils/__init__.py
  parlai/crowdsourcing/utils/acceptability.py
  parlai/mturk/core/mturk_manager.py
  parlai/mturk/tasks/turn_annotations/README
  parlai/mturk/tasks/turn_annotations/README.md
  parlai/mturk/tasks/turn_annotations/bot_agent.py
  parlai/mturk/tasks/turn_annotations/config/annotations_config.json
  parlai/mturk/tasks/turn_annotations/config/hit_config.json
  parlai/mturk/tasks/turn_annotations/config/left_pane_text.html
  parlai/mturk/tasks/turn_annotations/config/onboard_task_data.json
  parlai/mturk/tasks/turn_annotations/config/task_description.html
  parlai/mturk/tasks/turn_annotations/constants.py
  parlai/mturk/tasks/turn_annotations/launch.py
  parlai/mturk/tasks/turn_annotations/run.py
  parlai/mturk/tasks/turn_annotations/utils.py
  parlai/mturk/tasks/turn_annotations/worlds.py
  tests/nightly/gpu/test_crowdsourcing.py
Labels: CLA Signed

#3096 Fix description of Reddit BlenderBot3B models
  parlai/zoo/model_list.py
Labels: CLA Signed

#3098 Temporary compatibility note
  parlai/crowdsourcing/tasks/acute_eval/README.md
Labels: CLA Signed

#3097 Fix for flaky DialoGPT test
  tests/nightly/gpu/test_dialogpt.py
Labels: CLA Signed

#3053 [DOC DAY] ISH OSS static turn annotations
  parlai/crowdsourcing/tasks/turn_annotations_static/README.md
  parlai/crowdsourcing/tasks/turn_annotations_static/__init__.py
  parlai/crowdsourcing/tasks/turn_annotations_static/json/annotation_buckets.json
  parlai/crowdsourcing/tasks/turn_annotations_static/json/onboarding.json
  parlai/crowdsourcing/tasks/turn_annotations_static/json/onboarding_in_flight.jsonl
  parlai/crowdsourcing/tasks/turn_annotations_static/launch_config.py
  parlai/crowdsourcing/tasks/turn_annotations_static/run_task.py
  parlai/crowdsourcing/tasks/turn_annotations_static/turn_annotations_blueprint.py
  parlai/crowdsourcing/tasks/turn_annotations_static/webapp/.babelrc
  parlai/crowdsourcing/tasks/turn_annotations_static/webapp/package-lock.json
  parlai/crowdsourcing/tasks/turn_annotations_static/webapp/package.json
  parlai/crowdsourcing/tasks/turn_annotations_static/webapp/src/app.jsx
  parlai/crowdsourcing/tasks/turn_annotations_static/webapp/src/components/checkboxes.jsx
  parlai/crowdsourcing/tasks/turn_annotations_static/webapp/src/components/core_components.jsx
  parlai/crowdsourcing/tasks/turn_annotations_static/webapp/src/components/error_boundary.jsx
  parlai/crowdsourcing/tasks/turn_annotations_static/webapp/src/components/onboarding_components.jsx
  parlai/crowdsourcing/tasks/turn_annotations_static/webapp/src/components/task_components.jsx
  parlai/crowdsourcing/tasks/turn_annotations_static/webapp/src/css/style.css
  parlai/crowdsourcing/tasks/turn_annotations_static/webapp/src/main.js
  parlai/crowdsourcing/tasks/turn_annotations_static/webapp/src/static/index.html
  parlai/crowdsourcing/tasks/turn_annotations_static/webapp/webpack.config.js
Labels: CLA Signed

#3091 Test AcceptabilityChecker
  parlai/crowdsourcing/utils/acceptability.py
  tests/test_crowdsourcing.py
Labels: CLA Signed

#3104 Bump serialize-javascript from 2.1.2 to 3.1.0 in /parlai/crowdsourcing/tasks/turn_annotations_static/webapp
  parlai/crowdsourcing/tasks/turn_annotations_static/webapp/package-lock.json
  parlai/crowdsourcing/tasks/turn_annotations_static/webapp/package.json
Labels: CLA Signed, dependencies, javascript

#3094 Move torch.load/torch.save to PathManager.
  parlai/agents/drqa/drqa.py
  parlai/agents/drqa/model.py
  parlai/agents/ir_baseline/ir_baseline.py
  parlai/agents/seq2seq/seq2seq.py
  parlai/agents/starspace/starspace.py
  parlai/core/build_data.py
  parlai/core/image_featurizers.py
  parlai/core/teachers.py
  parlai/core/torch_agent.py
  parlai/core/torch_ranker_agent.py
  parlai/scripts/train_model.py
  parlai/scripts/vacuum.py
  parlai/tasks/image_chat/agents.py
  parlai/tasks/personality_captions/agents.py
  parlai/utils/torch.py
  projects/controllable_dialogue/controllable_seq2seq/controllable_seq2seq.py
  projects/image_chat/transresnet_multimodal/modules.py
  projects/image_chat/transresnet_multimodal/transresnet_multimodal.py
  projects/personality_captions/transresnet/modules.py
  projects/personality_captions/transresnet/transresnet.py
  projects/self_feeding/self_feeding_agent.py
  projects/wizard_of_wikipedia/wizard_transformer_ranker/wizard_transformer_ranker.py
Labels: CLA Signed

#3095 [dist] Allow non-tcp based distributed setup.
  parlai/core/metrics.py
  parlai/scripts/multiprocessing_eval.py
  parlai/scripts/multiprocessing_train.py
  parlai/scripts/train_model.py
  parlai/utils/distributed.py
  parlai/utils/logging.py
  parlai/utils/misc.py
Labels: CLA Signed

#3105 Prevent MTurk config folders from needing __init__.py
  parlai/crowdsourcing/tasks/turn_annotations_static/task_config/annotation_buckets.json
  parlai/crowdsourcing/tasks/turn_annotations_static/task_config/onboarding.json
  parlai/crowdsourcing/tasks/turn_annotations_static/task_config/onboarding_in_flight.jsonl
  parlai/crowdsourcing/tasks/turn_annotations_static/turn_annotations_blueprint.py
  parlai/mturk/tasks/turn_annotations/README.md
  parlai/mturk/tasks/turn_annotations/run.py
  parlai/mturk/tasks/turn_annotations/task_config/annotations_config.json
  parlai/mturk/tasks/turn_annotations/task_config/hit_config.json
  parlai/mturk/tasks/turn_annotations/task_config/left_pane_text.html
  parlai/mturk/tasks/turn_annotations/task_config/onboard_task_data.json
  parlai/mturk/tasks/turn_annotations/task_config/task_description.html
  tests/nightly/gpu/test_crowdsourcing.py
  tests/test_code.py
Labels: CLA Signed

#3070 Adding natural questions task
  parlai/core/build_data.py
  parlai/scripts/verify_data.py
  parlai/tasks/natural_questions/README.md
  parlai/tasks/natural_questions/__init__.py
  parlai/tasks/natural_questions/agents.py
  parlai/tasks/natural_questions/build.py
  parlai/tasks/natural_questions/utils/LICENSE
  parlai/tasks/natural_questions/utils/README.md
  parlai/tasks/natural_questions/utils/__init__.py
  parlai/tasks/natural_questions/utils/text_utils.py
  parlai/tasks/task_list.py
  requirements.txt
Labels: CLA Signed

#3108 Try to stabilize memnn.
  tests/test_memnn.py
Labels: CLA Signed

#3106 Update precommit config to include git-secrets
  .github/scripts/git-secrets
  .github/workflows/lint.yml
  .pre-commit-config.yaml
  parlai/core/script.py
  parlai/tasks/fromfile/agents.py
  parlai/zoo/glove_vectors/build.py
  parlai/zoo/tutorial_transformer_generator/build.py
  tests/datatests/test_new_tasks.py
  tests/nightly/gpu/test_bart.py
  tests/nightly/gpu/test_blended_skill_talk_gpu.py
  tests/nightly/gpu/test_controllable.py
  tests/tasks/convai2/test_convai2_worlds.py
  tests/test_apex.py
  tests/test_metrics.py
Labels: CLA Signed

#3083 [ImageFeaturizer] Detectron feature extraction
  .circleci/config.yml
  parlai/core/image_featurizers.py
  parlai/core/teachers.py
  parlai/utils/testing.py
  parlai/zoo/detectron/__init__.py
  parlai/zoo/detectron/build.py
  parlai/zoo/model_list.py
  tests/test_image_featurizers.py
Labels: CLA Signed

#3110 Coverage for more scripts
  parlai/scripts/profile_train.py
  parlai/scripts/token_stats.py
  parlai/scripts/vacuum.py
  tests/test_distributed.py
  tests/test_interactive.py
  tests/test_other_scripts.py
  tests/test_self_chat.py
Labels: CLA Signed

#3090 Better help message for --init-model
  parlai/core/params.py
Labels: CLA Signed

#3113 Seed messages from task flag in self chat
  parlai/scripts/self_chat.py
Labels: CLA Signed

#3122 swap lines in eval to have partial results
  parlai/scripts/eval_model.py
Labels: CLA Signed

#3125 Bump to v0.9.3.
  parlai/__init__.py
  setup.py
Labels: CLA Signed

#3124 AcceptabilityChecker README
  parlai/crowdsourcing/utils/README.md
Labels: CLA Signed

#3103 Porting ACUTE-Eval task to Hydra
  .gitignore
  parlai/crowdsourcing/tasks/acute_eval/README.md
  parlai/crowdsourcing/tasks/acute_eval/acute_eval_blueprint.py
  parlai/crowdsourcing/tasks/acute_eval/acute_eval_runner.py
  parlai/crowdsourcing/tasks/acute_eval/conf/example.yaml
  parlai/crowdsourcing/tasks/acute_eval/example_script.py
  tests/test_code.py
Labels: CLA Signed

#3123 Return text for all hyps in the beam from TorchGenerator
  parlai/core/torch_generator_agent.py
  tests/test_transformers.py
Labels: CLA Signed

#3129 [data] Convert TaskMaster-2 to PathManager.
  parlai/tasks/taskmaster2/agents.py
Labels: CLA Signed

#3134 Add jga metric to taskmaster2
  parlai/tasks/taskmaster2/agents.py
Labels: CLA Signed

#3117 Test parlai/core/script.py
  parlai/__main__.py
  parlai/core/script.py
  tests/test_script.py
Labels: CLA Signed

#3135 Add taskmaster2 command-line arg to specify subset of domains
  parlai/tasks/taskmaster2/agents.py
Labels: CLA Signed

#3137 Using the ParlAI color
  docs/source/_static/css/parlai_theme.css
  website/static/css/home-theme.css
  website/static/css/parlai.css
  website/templates/home.html
Labels: CLA Signed
