Repository facebookresearch/ParlAI, pull requests merged in 2021-12, with the labels that each got.

#4197 Curated response generators
  parlai/utils/curated_response.py
  tests/test_utils.py
Labels: CLA Signed

#4224 Fix cleaninstall test breakage
  requirements.txt
Labels: CLA Signed

#4223 See if I can fix crowdsourcing jslint pre-commit hook error
  parlai/crowdsourcing/package.json
Labels: CLA Signed

#4218 Save conversations check for parent directory
  parlai/utils/conversations.py
Labels: CLA Signed

#4227 [FiD] Add specialized chunking to search engine retrievers
  parlai/agents/fid/fid.py
  parlai/agents/rag/retrievers.py
  tests/nightly/gpu/test_rag.py
Labels: CLA Signed

#4221 [BlenderBot2] A hybrid mode (skip search when needed)
  .circleci/config.yml
  parlai/tasks/wizard_of_internet/agents.py
  parlai/tasks/wizard_of_internet/constants.py
  parlai/tasks/wizard_of_internet/test/wizard_of_internet_WizardDialogGoldKnowledgeTeacher_test.yml
  parlai/tasks/wizard_of_internet/test/wizard_of_internet_WizardDialogGoldKnowledgeTeacher_train.yml
  parlai/tasks/wizard_of_internet/test/wizard_of_internet_WizardDialogGoldKnowledgeTeacher_valid.yml
  projects/blenderbot2/agents/blenderbot2.py
  projects/blenderbot2/agents/modules.py
  projects/blenderbot2/agents/sub_modules.py
Labels: CLA Signed

#4229 [SaFeRDialogues] dataset and model release
  parlai/tasks/saferdialogues/LICENSE
  parlai/tasks/saferdialogues/README.md
  parlai/tasks/saferdialogues/__init__.py
  parlai/tasks/saferdialogues/agents.py
  parlai/tasks/saferdialogues/build.py
  parlai/tasks/saferdialogues/test.py
  parlai/tasks/saferdialogues/test/saferdialogues_test.yml
  parlai/tasks/saferdialogues/test/saferdialogues_train.yml
  parlai/tasks/saferdialogues/test/saferdialogues_valid.yml
  parlai/tasks/task_list.py
  parlai/zoo/model_list.py
  parlai/zoo/saferdialogues/__init__.py
  parlai/zoo/saferdialogues/build.py
  projects/saferdialogues/README.md
Labels: CLA Signed

#4151 Improve error message in Teachers
  parlai/core/teachers.py
Labels: CLA Signed, stale

#4242 Fix lr scheduler tests & lr schedulers
  parlai/nn/lr_scheduler.py
  tests/test_lr_schedulers.py
Labels: CLA Signed

#4021 [slurm] Lower scope of exception catch
  parlai/utils/distributed.py
Labels: CLA Signed, never-stale

#4196 Fix "Warmup scheduler is loaded from the state dict, even when initializing fresh"
  parlai/nn/lr_scheduler.py
Labels: CLA Signed

#4236 Fix Crowdsourcing Tests after mephisto hydra upgrade
  parlai/crowdsourcing/tasks/acute_eval/fast_eval.py
  parlai/crowdsourcing/tasks/acute_eval/util.py
  parlai/crowdsourcing/utils/tests.py
  tests/crowdsourcing/tasks/acute_eval/test_acute_eval.py
  tests/crowdsourcing/tasks/acute_eval/test_fast_acute_dataset.py
  tests/crowdsourcing/tasks/acute_eval/test_fast_acute_logs.py
  tests/crowdsourcing/tasks/acute_eval/test_fast_acute_self_chat.py
  tests/crowdsourcing/tasks/model_chat/test_model_chat.py
  tests/crowdsourcing/tasks/model_chat/test_model_image_chat.py
  tests/crowdsourcing/tasks/qa_data_collection/test_qa_data_collection.py
  tests/crowdsourcing/tasks/test_chat_demo.py
  tests/crowdsourcing/tasks/turn_annotations_static/test_turn_annotations_static.py
Labels: CLA Signed

#4232 [TOD][Agents] Helper Agents for simulation + tests
  parlai/core/tod/tod_agents.py
  parlai/core/tod/tod_test_utils/__init__.py
  parlai/core/tod/tod_test_utils/test_agents.py
  tests/tod/test_tod_agents_and_teachers.py
Labels: CLA Signed

#4239 [LIGHT] AIMOY
  parlai/agents/reranker/README.md
  parlai/agents/reranker/__init__.py
  parlai/agents/reranker/reranker.py
  parlai/zoo/light_whoami/__init__.py
  parlai/zoo/light_whoami/automated_expanded_attention_1024.py
  parlai/zoo/light_whoami/expanded_and_multiobjective_1024.py
  parlai/zoo/light_whoami/multiobjective.py
  parlai/zoo/light_whoami/profile_expanded_attention_1024.py
  parlai/zoo/light_whoami/profile_expanded_attention_128.py
  parlai/zoo/light_whoami/rpa_reranker.py
  parlai/zoo/light_whoami/rpa_reranker_auto_expanded_attention.py
  parlai/zoo/light_whoami/rpa_ul_1024.py
  parlai/zoo/light_whoami/rpa_ul_128.py
  parlai/zoo/light_whoami/test_rpa_reranker.py
  parlai/zoo/light_whoami/vanilla_1024.py
  parlai/zoo/light_whoami/vanilla_128.py
  parlai/zoo/light_whoami/whoami_download.py
  parlai/zoo/model_list.py
  projects/light_whoami/README.md
  projects/light_whoami/agents/__init__.py
  projects/light_whoami/agents/expanded_attention.py
  projects/light_whoami/agents/multi_objective.py
  projects/light_whoami/agents/pacer.py
  projects/light_whoami/agents/poly_return_weights.py
  projects/light_whoami/agents/rpa_rerank.py
  projects/light_whoami/agents/rpa_ul.py
  projects/light_whoami/task/__init__.py
  projects/light_whoami/task/agents.py
  projects/light_whoami/task/mutators.py
  projects/light_whoami/task/utils.py
  tests/nightly/gpu/test_light_whoami.py
Labels: CLA Signed

#4251 add K2R to main project page
  projects/README.md
Labels: CLA Signed

#4252 Add Am I me or you to LIGHT page
  projects/light/README.md
Labels: CLA Signed

#4253 [WizInt] fixing the problem with teacher test
  parlai/tasks/wizard_of_internet/agents.py
Labels: CLA Signed

#4254 [Crowdsourcing] can call blueprints from command line
  parlai/crowdsourcing/README.md
  parlai/crowdsourcing/tasks/model_chat/README.md
  parlai/crowdsourcing/tasks/model_chat/run_image_chat.py
  parlai/crowdsourcing/tasks/turn_annotations_static/README.md
  parlai/crowdsourcing/tasks/turn_annotations_static/run_in_flight_qa.py
  tests/crowdsourcing/tasks/model_chat/test_model_image_chat.py
Labels: CLA Signed

#4238 [BB2] Handling increase in batch size from dynamic batching
  projects/blenderbot2/agents/modules.py
Labels: CLA Signed

#4233 [TOD][Teachers] Add TOD Teachers + base Parser agent
  conftest.py
  parlai/core/teachers.py
  parlai/core/tod/README.md
  parlai/core/tod/teacher_metrics.py
  parlai/core/tod/tod_agents.py
  parlai/core/tod/tod_core.py
  pytest.ini
  tests/tod/__init__.py
  tests/tod/test_tod_teacher_metrics.py
Labels: CLA Signed

#4249 [TOD][Agents] Helper Agents for simulation + tests
  parlai/core/tod/tod_agents.py
  parlai/core/tod/tod_test_utils/__init__.py
  parlai/core/tod/tod_test_utils/test_agents.py
  tests/tod/test_tod_agents_and_teachers.py
Labels: CLA Signed

#4178 [TOD] World, world metrics, script, tests
  parlai/core/tod/README.md
  parlai/core/tod/tod_agents.py
  parlai/core/tod/tod_test_utils/standalone_api_file.pickle
  parlai/core/tod/tod_world.py
  parlai/core/tod/world_metrics.py
  parlai/core/tod/world_metrics_handlers.py
  parlai/scripts/distributed_tod_world_script.py
  parlai/scripts/tod_world_script.py
  projects/tod_simulator/README.md
  projects/tod_simulator/world_metrics/extended_world_metrics.py
  tests/tod/test_tod_world_and_script.py
  tests/tod/test_tod_world_metrics.py
  tests/tod/test_tod_world_metrics_in_script.py
  tests/tod/test_tod_world_script_metrics.py
Labels: CLA Signed

#4180 [TOD][straightforward] Tod world output jsonl structure to teacher task
  parlai/core/tod/tod_agents.py
  parlai/core/tod/tod_core.py
  parlai/tasks/tod_json/README.md
  parlai/tasks/tod_json/__init__.py
  parlai/tasks/tod_json/agents.py
  parlai/tasks/tod_json/example_data.jsonl
  tests/test_zootasks.py
Labels: CLA Signed

#4181 [TOD][Dataset][Easy] Google SGD in TOD Conversations format
  parlai/tasks/google_sgd/agents.py
  parlai/tasks/google_sgd/build.py
  parlai/tasks/google_sgd/test.py
  parlai/tasks/google_sgd/test/google_sgd_UserSimulatorTeacher_test.yml
  parlai/tasks/google_sgd/test/google_sgd_UserSimulatorTeacher_train.yml
  parlai/tasks/google_sgd/test/google_sgd_UserSimulatorTeacher_valid.yml
  parlai/tasks/google_sgd/test/google_sgd_test.yml
  parlai/tasks/google_sgd/test/google_sgd_train.yml
  parlai/tasks/google_sgd/test/google_sgd_valid.yml
Labels: CLA Signed

#4271 Fix crowdsourcing CI check
  .circleci/config.yml
Labels: CLA Signed

#4184 [TOD][Datasets][Easy] MSR E2E into TOD Conversations format
  parlai/tasks/msr_e2e/__init__.py
  parlai/tasks/msr_e2e/agents.py
  parlai/tasks/msr_e2e/build.py
  parlai/tasks/msr_e2e/test.py
  parlai/tasks/msr_e2e/test/msr_e2e_SystemTeacher_test.yml
  parlai/tasks/msr_e2e/test/msr_e2e_SystemTeacher_train.yml
  parlai/tasks/msr_e2e/test/msr_e2e_SystemTeacher_valid.yml
  parlai/tasks/msr_e2e/test/msr_e2e_UserSimulatorTeacher_test.yml
  parlai/tasks/msr_e2e/test/msr_e2e_UserSimulatorTeacher_train.yml
  parlai/tasks/msr_e2e/test/msr_e2e_UserSimulatorTeacher_valid.yml
  parlai/tasks/task_list.py
Labels: CLA Signed

#4185 [TOD][Datasets][Easy] Multidogo -> TOD Conversations format
  parlai/tasks/multidogo/__init__.py
  parlai/tasks/multidogo/agents.py
  parlai/tasks/multidogo/build.py
  parlai/tasks/multidogo/test.py
  parlai/tasks/multidogo/test/multidogo_SystemTeacher_multidogo-domains=software_test.yml
  parlai/tasks/multidogo/test/multidogo_SystemTeacher_multidogo-domains=software_train.yml
  parlai/tasks/multidogo/test/multidogo_SystemTeacher_multidogo-domains=software_valid.yml
  parlai/tasks/multidogo/test/multidogo_UserSimulatorTeacher_multidogo-domains=software_test.yml
  parlai/tasks/multidogo/test/multidogo_UserSimulatorTeacher_multidogo-domains=software_train.yml
  parlai/tasks/multidogo/test/multidogo_UserSimulatorTeacher_multidogo-domains=software_valid.yml
  parlai/tasks/task_list.py
Labels: CLA Signed

#4186 [TOD][Datasets][Easyish] MultiWoz V2.2 in Conversations Format
  parlai/tasks/multiwoz_v22/README.md
  parlai/tasks/multiwoz_v22/__init__.py
  parlai/tasks/multiwoz_v22/agents.py
  parlai/tasks/multiwoz_v22/build.py
  parlai/tasks/multiwoz_v22/build_sha_check_script.py
  parlai/tasks/multiwoz_v22/test.py
  parlai/tasks/multiwoz_v22/test/multiwoz_v22_UserSimulatorTeacher_test.yml
  parlai/tasks/multiwoz_v22/test/multiwoz_v22_UserSimulatorTeacher_train.yml
  parlai/tasks/multiwoz_v22/test/multiwoz_v22_UserSimulatorTeacher_valid.yml
  parlai/tasks/multiwoz_v22/test/multiwoz_v22_test.yml
  parlai/tasks/multiwoz_v22/test/multiwoz_v22_train.yml
  parlai/tasks/multiwoz_v22/test/multiwoz_v22_valid.yml
  parlai/tasks/task_list.py
Labels: CLA Signed

#4189 [TOD][Datasets][Easy] Taskmaster(1) in Conversations format
  parlai/tasks/taskmaster/agents.py
  parlai/tasks/taskmaster/build.py
  parlai/tasks/taskmaster/test.py
  parlai/tasks/taskmaster/test/taskmaster_SystemTeacher_test.yml
  parlai/tasks/taskmaster/test/taskmaster_SystemTeacher_train.yml
  parlai/tasks/taskmaster/test/taskmaster_SystemTeacher_valid.yml
  parlai/tasks/taskmaster/test/taskmaster_UserSimulatorTeacher_test.yml
  parlai/tasks/taskmaster/test/taskmaster_UserSimulatorTeacher_train.yml
  parlai/tasks/taskmaster/test/taskmaster_UserSimulatorTeacher_valid.yml
Labels: CLA Signed

#4188 [TOD][Datasets][Easy] Taskmaster2 to TOD Conversations format
  parlai/tasks/taskmaster2/README.md
  parlai/tasks/taskmaster2/agents.py
  parlai/tasks/taskmaster2/build.py
  parlai/tasks/taskmaster2/test.py
  parlai/tasks/taskmaster2/test/taskmaster2_UserSimulatorTeacher_test.yml
  parlai/tasks/taskmaster2/test/taskmaster2_UserSimulatorTeacher_train.yml
  parlai/tasks/taskmaster2/test/taskmaster2_UserSimulatorTeacher_valid.yml
  parlai/tasks/taskmaster2/test/taskmaster2_test.yml
  parlai/tasks/taskmaster2/test/taskmaster2_train.yml
  parlai/tasks/taskmaster2/test/taskmaster2_valid.yml
Labels: CLA Signed

#4187 [TOD][Datasets][Easy] Taskmaster3 (TicketTalk) to TOD Structured format
  parlai/tasks/task_list.py
  parlai/tasks/taskmaster3/__init__.py
  parlai/tasks/taskmaster3/agents.py
  parlai/tasks/taskmaster3/build.py
  parlai/tasks/taskmaster3/test.py
  parlai/tasks/taskmaster3/test/taskmaster3_SystemTeacher_test.yml
  parlai/tasks/taskmaster3/test/taskmaster3_SystemTeacher_train.yml
  parlai/tasks/taskmaster3/test/taskmaster3_SystemTeacher_valid.yml
  parlai/tasks/taskmaster3/test/taskmaster3_UserSimulatorTeacher_test.yml
  parlai/tasks/taskmaster3/test/taskmaster3_UserSimulatorTeacher_train.yml
  parlai/tasks/taskmaster3/test/taskmaster3_UserSimulatorTeacher_valid.yml
Labels: CLA Signed

#4272 Use external database in crowdsourcing code
  parlai/crowdsourcing/utils/analysis.py
  tests/crowdsourcing/test_analysis.py
Labels: CLA Signed

#4270 [bug fix] Torch Classifier agent should call self.backward(loss)
  parlai/core/torch_classifier_agent.py
Labels: CLA Signed
